### ISSUE TITLE
find a valid default value for 'edit_by'

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#10]
Android users do not have a @use_full_name so this remains NULL

It is really important to know who captured which record. Ideally we would use @mergin_username but that is not implemented yet. 

So what other variable can we use that identifies the user or their device?

Once you have this, use it to style the points so surveyors can see who captured each point, so they don't edit someone else's record

If you can't find something that works, then expose it in the form and make it a value relation to a surveyor lookup table with (Zach, Thabitha, Agnes, Letticia, Johannes)

**Comment by seabilwe** [comment]
With regards to the lookup table, do I use their Mergin usernames or in the manner you've indicated them by?

**Comment by seabilwe** [comment]
Complete!
- Added a lookup table
