### ISSUE TITLE
Verify the accuracy of the information provided in 11.3

### ISSUE THREAD

**Issue by seabilwe** [kartoza/WBR-SEMP#115]
11.3 Climate:

- [x] Are the data accurate?? Data from where

11.3.1 Average temperature of the warmest month: between 25 to 28 °C
11.3.2 Average temperature of the coldest month: between 14 to 19 °C
11.3.3 Mean annual precipitationbetween 600 to 900 mm, recorded at an elevation of _______ metres

- [x] Is this list complete, are the data accurate??

11.3.4 Is there a meteorological station in or near the proposed biosphere reserve? If so, what is its name and location and how long has it been operating?
Lephalale
Thabazimbi
Mokopane
Bela-Bela

**Comment by seabilwe** [comment]
> Is this list complete, are the data accurate??
> 11.3.4 Is there a meteorological station in or near the proposed biosphere reserve? If so, what is its name and location and how long has it been operating?

Data Source: South African Weather Services Data Request

Stations are accurate, but according to this list from July 2021, here is the list of meteorological stations:

| ClimNo | Station Name | Height | Description | Current Order |
| -------| ------------| -------| -------------| ------------- |
| 0587214 6 |	BUFFELDOORNS ARS |	967 |	Central Forecating Office|	ELEC_RAIN|
| 0674341 8 |	LEPHALALE |	839|	Pietersburg|	ELEC_TEMP |
| 0675666 2 |	MARKEN |	1,001|	Pietersburg|	ELEC_TEMP |
| 0633882 7|    MOKOPANE |	1,107|	Pietersburg|	ELEC_TEMP |
| 0632123 1 |	STEENBOKFONTEIN ARS |	1,317|	Pietersburg|	ELEC_RAIN|
| 0587263 0 |	SWARTKLIP NOOITGEDACHT ARS |	996|	Central Forecating Office|	ELEC_RAIN |
| 0587725CX |	THABAZIMBI |	977|	Central Forecating Office| 	ELEC_TEMP|
| 0718844 0 |	TOM BURKE S.A.P.S. ARS |	813|	Pietersburg|	ELEC_RAIN |
| 0589594 1 |	WARMBAD TOWOOMBA |	1,143|	Central Forecating Office| ELEC_TEMP |

Weather Station Map:
![weather-station-map](https://user-images.githubusercontent.com/56301949/220294367-cef85f8f-3f83-4713-91d0-0aca050a0580.png)

**Comment by seabilwe** [comment]
**11.3.1 Average temperature of the warmest month:** 
- Maximum temperatures range between 25 and 32°C, but can reach extremes of up to 42°C
- Minimum temperatures range between 6 and 18 °C

**11.3.2 Average temperature of the coldest month:**
- Temperatures range between 14 and 22 °C, but can reach extremes of 32 °C
- Minimum temperatures range between 10 and 4 °C

**11.3.3 Mean annual precipitation between ______ , recorded at an elevation of _______ metres**
- Mean annual precipitation ranges between 300 and  900mm recorded at elevations between 800 and 1400 m.

**References:**
- Isaacs, L., Somers, M.J. and Swanepoel, L.H., 2022. Density of African Civets in a Moist Mountain Bushveld Region of South Africa. Small Carnivores: Evolution, Ecology, Behaviour and Conservation, p.249.
- Swanepoel, L.H., 2009. Ecology and conservation of leopards, Panthera pardus, on selected game ranches in the Waterberg region, Limpopo, South Africa (Doctoral dissertation, University of Pretoria).
- Matukana, V., 2021. The Survival of Acacia decurrens, Acacia melanoxylon and Populus alba in Vaalwater, Waterberg Biosphere Reserve, Limpopo Province, South Africa (Doctoral dissertation).
- Kupchella, C.E. and Hyland, M.C., 1993. Environmental Science: Living within the system of nature. Prentice Hall International.

**Comment by RAP-ZAUK** [comment]
Thanks
