### ISSUE TITLE
maps.wbr landing page improvements

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/WBR-SEMP#117]
Add new images to the landing page that focuses on WBR, @seabilwe If you have any images you think are suited here please add them to this ticket and I will update the site

**Comment by seabilwe** [comment]
@NyakudyaA, I got these from Letticia

![IMG-20200710-WA0032](https://user-images.githubusercontent.com/56301949/218108507-3a563015-3154-4625-a01f-0bdb94ada54b.jpg)
![IMG-20200903-WA0119](https://user-images.githubusercontent.com/56301949/218108529-3c7f1b42-218f-4430-878f-162e6538dc74.jpg)
![WBR Tamboti](https://user-images.githubusercontent.com/56301949/218108541-1ef3e4a4-2d2b-45da-8113-f9354a5e91cc.jpg)
![WBR water source](https://user-images.githubusercontent.com/56301949/218108552-eb69c242-5a98-4090-9885-a1a4b71ae719.jpg)
![WBR landscape](https://user-images.githubusercontent.com/56301949/218108564-4abbb6be-1964-4914-818f-36e18ba2f14a.jpg)
![WBR wilderness](https://user-images.githubusercontent.com/56301949/218108569-9657dd0a-be18-4fbb-9f57-2ab9c147a399.jpg)
![MK photography 012](https://user-images.githubusercontent.com/56301949/218108575-08e3ee3f-c496-4e79-8efb-5c9d47299ec0.jpg)

**Comment by NyakudyaA** [comment]
The site has been updated by doing the following
* Copy the images into `static/frontend/images/home/`
* remove the section where images had links in `./frontend/templates/frontend/include/home.html`
