### ISSUE TITLE
Acquire or Extract Polygons for the Old WBR Boundaries

### ISSUE THREAD

**Issue by seabilwe** [kartoza/WBR-SEMP#119]
At the moment, the old WBR boundary dataset available does not contain zones as part of the data. 

You need to either:

- [x] Extract polygons from the DEFF service https://portal.environment.gov.za/server/rest/services/SACAD 
- [x] Acquire polygons

**Remember to:** 
- [x] Store the data in the database

**Comment by seabilwe** [comment]
@gubuntu should I upload this layer in the WBR db or the kartoza one?
![image](https://user-images.githubusercontent.com/56301949/222425215-1432074a-1b5a-41ca-83ed-5909e0038807.png)

**Comment by gubuntu** [comment]
nice - in wbr db

**Comment by seabilwe** [comment]
# Notes 

The service link from the DEFF Data on Conservation Areas (SACAD).
  - https://portal.environment.gov.za/server/rest/services/SACAD

When a connection in QGIS is added, the service provides two sets of layers, WFS and a WCS (image below)
![image](https://user-images.githubusercontent.com/56301949/222435305-1ddf3163-4e13-4315-81c3-cddc3f9c1829.png)

- The feature service layers (buffer, core, and transition) were clipped to the Waterberg Biosphere Reserve current boundary
- Followed by merging the layers into one, and
- Exporting the layer to the wbr database

Layer named 'current_wbr_zonation' uploaded to the public schema in the wbr db
![image](https://user-images.githubusercontent.com/56301949/222431804-e8189bcd-2f5c-4fcc-9b9b-df416031c6d3.png)
