### ISSUE TITLE
make an offline theme

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#15]
- [x] make a theme with a local basemap called 'offline local basemap'
 For the local basemap, prepare a GeoPackage covering the survey area, with basic features like roads and points of interest. It must be a separate geopackage to the one containing the survey points. You can base it on the one I did for STI or ask Tim, he did one for SA as well (though it must be clipped to minimised its size)
- [x] add https://github.com/kartoza/WBR-SEMP/blob/master/survey_villages.geojson to the geopackage you created above and add it as a layer to all three themes, styled with https://github.com/kartoza/WBR-SEMP/blob/master/survey_villages.qml

**Comment by seabilwe** [comment]
By what time will you need everything to be added?

**Comment by seabilwe** [comment]
I have not come across any material you did for STI, can I  get a link perhaps

**Comment by seabilwe** [comment]
@gubuntu I have created the other GeoPackage and have added the _survey_villages_ layer and added the style to the layer, but now my problem with the style is that when i load it, its a plain point layer.
-The first Offline base map on the list I had already added it to the main GeoPackage. 
-With regards to the edit_by option I opted for the lookup table.

**Comment by seabilwe** [comment]
![hhhh2](https://user-images.githubusercontent.com/56301949/86151774-77f20d00-baff-11ea-957e-52c387538cc4.PNG)
Here are the themes in the second GeoPackage

**Comment by gubuntu** [comment]
I've shared the STI_People project with you, jsut with read permission for now. Download it and have a look in QGIS, especially at the local basemap theme. Also look at the form, I'd like to chat about it tomorrow (Weds) afternoon to brief you on doing some work on it. 

Looks like you put the wrong screenshot above. 

I see you have the village and poi layers in the other geopackage but haven't added them to the project yet. Please do, as per my previous note about which themes and style yourself if mine doesn't work, or tweak mine to make it work. Might be a slight change in field names going from gpkg to geojson to gpkg?

**Comment by seabilwe** [comment]
I have added also the Waterberg district boundary and the Limpopo province boundary, I added roads but they were incomplete. The survey village points are added as well. All data to be displayed in the map canvas has been grouped

**Comment by gubuntu** [comment]
did you get / see @timlinux's Mergin SA basemap project

**Comment by seabilwe** [comment]
No I did not

**Comment by seabilwe** [comment]
![image](https://user-images.githubusercontent.com/56301949/86230285-2b571200-bb91-11ea-802e-a1df311dab77.png)
![image](https://user-images.githubusercontent.com/56301949/86231048-38283580-bb92-11ea-9291-c6dd0022fee2.png)
http://www.sasdi.net/sresults.aspx?text=census
This is the link that I found and I was given also there is no link that leads me to download the data, but I'm waiting on someone who is my last hope

**Comment by gubuntu** [comment]
make a copy of the context.gpkg outside the project folder and build in some more data asap and review with me before we add it back to the project

**Comment by seabilwe** [comment]
Okay

**Comment by seabilwe** [comment]
@gubuntu here is the context gpkg
[context.zip](https://github.com/kartoza/WBR-SEMP/files/4859676/context.zip)

**Comment by seabilwe** [comment]
@gubuntu I received the dwellings data and have clipped the Waterberg district. Where should the data be added?

**Comment by seabilwe** [comment]
[Dwellings.zip](https://github.com/kartoza/WBR-SEMP/files/4862567/Dwellings.zip)
Here is the clipped dwellings data.
