### ISSUE TITLE
improve 'years without water'

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#16]
be able to capture smaller periods and also (in another field?) irregular supply e.g. only certain days per week or only certain hours per day e.g. Leseding extension 5 1am - 7am

**Comment by seabilwe** [comment]
@gubuntu I saw on the group, they mentioned the addition of **buckets** as another method of collecting water, has that been confirmed as well?

**Comment by gubuntu** [comment]
note I haven't assigned this to you - I'm working on it this evening so please don't otherwise we get conflicts. I'll create tickets for you for anything I don't manage to fix tonight

and the buckets issue is separate so shouldn't be discussed in this ticket - but I have added it to the project.

**Comment by gubuntu** [comment]
please think about this and propose a solution

**Comment by seabilwe** [comment]
@gubuntu  I was going through ways in which **days per week or only certain hours per day**, maybe we could have separate fields one for **hours** (still looking)   and the other for **days** [ day(age(now(),"creation_date")) **OR** to_date('2020-06-01') - to_date(now()) ] and for the creation date have a calendar pop-up (I saw the option that allows one to pick)
