### ISSUE TITLE
source heritage data

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#17]
- [x] check that data on heritage sites is listed in the catalog sheet
- [x] check that we have the latest available data from SAHRA in the kartozagis.sahra schema in postgis.kartoza.com
- [x] check whether these two sites are recorded in the SAHRA data set: MADIMATLE MOUNTAIN AND GATKOP CAVES SITUATED ON THE REMAINDER OF THE FARM DONKERPOORT 448 KQ AND REMAINDER OF THE FARM RANDSTEPHNE 455 KQ, THABAZIMBI. If they are not, create a new point layer in a 'wbr' schema and capture them. @zacharlie I propose that we use this 'wbr' project schema to store any data we capture for this project, that is not in publicly available data sets in the other source schemas (to put in your SOP)

**Comment by seabilwe** [comment]
@gubuntu 
1. Catalog sheet: The only heritage site data listed is the World Heritage Site data from DEFF
2. postgis.katoza.com : I looked for kartozagis.sahra schema in postgis.kartoza.com and it's not there, which schema the data is in?

**Comment by seabilwe** [comment]
Acquired heritage site data sets (in a form a spreadsheet):
  - Provincial
  - National
-Both for the whole country.
-Extracted provincial heritage sites and added Madimatle Mountain and Gatkop Caves to the layer. 
-A **heritage site** layer will be added to the wbr schema with Madimatle, Gatkop Caves and Makapans Caves added as well

**Comment by seabilwe** [comment]
@gubuntu  here is the SAHRA data set
[sahra.zip](https://github.com/kartoza/WBR-SEMP/files/4959958/sahra.zip)

**Comment by NyakudyaA** [comment]
> @gubuntu here is the SAHRA data set
> [sahra.zip](https://github.com/kartoza/WBR-SEMP/files/4959958/sahra.zip)

Will DM you the database credentials soon and you can load the data into the database
