### ISSUE TITLE
set up dedicated WBR database asap

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#18]
WBR survey data and some other project-specific data needs a dedicated database. I think this calls for a dedicated host with

- [x] Pg
- [x] pgAdmin
- [x] Lutra PG mergin agent https://github.com/lutraconsulting/mergin-db-sync
- [x] metabase https://www.metabase.com/

Rope in @lucernae and @meomancer to help. Delegate to @zacharlie if you can't start soon

**Comment by NyakudyaA** [comment]
> WBR survey data and some other project-specific data needs a dedicated database. I think this calls for a dedicated host with
> 
>     * [ ]  Pg
> 
>     * [ ]  pgAdmin
> 
>     * [ ]  Lutra PG mergin agent
> 
>     * [ ]  metabase

Maybe we can use the Kirchoff one since we were going to be taking it down. I can delete the services on that machine and install these

**Comment by gubuntu** [comment]
good idea, I've renamed the Hetzner Kirchhoff project to WBR to start

**Comment by gubuntu** [comment]
@lucernae the mergin project to test is martin/WBRFieldWork-dbsync. You can create an account on mergin for yourself and we'll ask @dodobas to share with you, or we create a 'KartozaPG' user

**Comment by lucernae** [comment]
my mergin user account is `lucernae`

**Comment by NyakudyaA** [comment]
> WBR survey data and some other project-specific data needs a dedicated database. I think this calls for a dedicated host with
> 
>     * [x]  Pg
> 
>     * [x]  pgAdmin
> 
>     * [ ]  Lutra PG mergin agent https://github.com/lutraconsulting/mergin-db-sync
> 
>     * [x]  metabase https://www.metabase.com/
> 
> 
> Rope in @lucernae and @meomancer to help. Delegate to @zacharlie if you can't start soon

@lucernae I have set up the stack above but I am unsure how we need to proceed with setting up the Lutra PG mergin agent. Do we need to run this as part of PostgreSQL initialization scripts or do we need to dockerize this?

**Comment by gubuntu** [comment]
@dodobas is building a Dockerfile for the mergin-dbsync agent so please deploy and configure as soon as it's ready

**Comment by gubuntu** [comment]
@lucernae the Dockerfile for the mergn-db-sync agent is ready at https://github.com/lutraconsulting/mergin-db-sync, please use it to deploy asap

**Comment by NyakudyaA** [comment]
This has been implemented and working
