### ISSUE TITLE
find and recover Zach's and other early missing survey records

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#19]
including Boschdraai and Alma

also remove dud testing records from Vaalwater  (Gavin)

**Comment by seabilwe** [comment]
Just to confirm @gubuntu , the records that I need to remove are from the 30th of June 2020 only

**Comment by gubuntu** [comment]
yes, just 30 June

**Comment by seabilwe** [comment]
Okay

**Comment by seabilwe** [comment]
@gubuntu I just spoke to Saber about the missing records and he says that it could be that the records were on the device but were never synced to the server, and if it is that case they cannot can be recovered

I remember Letticia mentioned in passing that she would go to those villages that have missing records and sample what is left

**Comment by seabilwe** [comment]
- Missing Alma points collected:
![image](https://user-images.githubusercontent.com/56301949/95387392-f0cbe680-08f0-11eb-8385-90a7c90b2721.png)

- Missing Boschdraai points collected:
![image](https://user-images.githubusercontent.com/56301949/95387519-1ce76780-08f1-11eb-86d0-20ec6c0340ee.png)

- Missing points from Bokwidi:
  ---to be collected

-Nyakelang, Rooisloot, GaMoshidi and Rhenosterfontein are small villages with very little houses, therefore the number of houses sampled will be less.
