### ISSUE TITLE
create tables for value maps

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#20]
For each field that has a value map in the WBR Survey form in the QGIS project, create a table in the wbr.kartoza.com:gis.wbr_survey schema with the naming convention `fieldname_valuemap`

**Comment by seabilwe** [comment]
@gubuntu I checked everything in the tables and fixed the Boolean issue...those fields are not value maps anymore and I have removed the associated tables from the _wbr.kartoza.com:gis.wbr_survey_ schema

**Comment by gubuntu** [comment]
what are the computer, radio and television tables?

Have a look at the `survey_reporting_prep.sql` to see how I'm using the lookup tables and valuemap tables to merge everything into a nice table, equivalent of doing the geopackage export with all lookups populated

**Comment by seabilwe** [comment]
The radio, computer and television tables are in the schema.

Okay, I will go through it

**Comment by gubuntu** [comment]
they must have the same naming convention as the other tables.

**Comment by seabilwe** [comment]
I fixed that
