### ISSUE TITLE
route port 3000 to /

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#21]
metabase should be the default page at at https://wbr.kartoza.com

**Comment by gubuntu** [comment]
ping @lucernae

**Comment by lucernae** [comment]
@gubuntu who should I contact to get this Metabase app access?

**Comment by gubuntu** [comment]
@lucernae I'm sure you set it up? That machine also has WBR postgis and mergin-pg-agent on it...

Or are you asking for a user account on metabase?

**Comment by zacharlie** [comment]
@lucernae so basically we should set up an nginx proxy to expose the metabase application directly on the root URL of wbr.kartoza.com, SSL should be applied, and PGadmin should probably be exposed (via a rewrite) from the active port to https://wbr.kartoza.com/pgadmin

**Comment by gubuntu** [comment]
this was done at some point but it's broken since
