### ISSUE TITLE
Survey reporting

### ISSUE THREAD

**Issue by seabilwe** [kartoza/WBR-SEMP#26]
Use data collected from the field to 
- [x] identify and deal with duplicates, logical inconsistencies, errors etc. 
- report on summary statistics
  - [x] overall
  - [x] by village
- [x] rank villages according to access to water,
- [x] distance travelled to get water, 
- [x] mean income 
- [x] potential for irrigation
- etc.

this is to get an idea of which village needs more attention

**Comment by gubuntu** [comment]
@seabilwe rather list the data to acquire in the data catalog sheet

**Comment by seabilwe** [comment]
Wil complete today
