### ISSUE TITLE
Cleaning the WBR Data Catalogue

### ISSUE THREAD

**Issue by seabilwe** [kartoza/WBR-SEMP#27]
- [x] @zacharlie git hub won't allow me to assign this to both of us, but basically we need to clean the catalog...if there is anything you need me to do, please shout
**WBR Catalog**: https://docs.google.com/spreadsheets/d/1YcjZBvjQCethojZdoSNMEYNLa5lXar6SAxGuWG6HX1A 

**Add these to catalogue:**

- [ ] Temperature and  rainfall (per grid square) with the date (rainfall must have isohyets)

- [ ] Downscale climate change model outputs (ideally 2020, 2050, 2100)

- [x] Vegetation data, (already in the database) - To be used to determine corridors and climate envelopes

- [x] Include invasive vegetation dataset

- [ ] Land use, especially rainfed agriculture and irrigated areas

- [x] Ecological infrastructure, especially water infrastructure (refer to Holness)

- [x] BirdLife Boundary from IBA

- [x] Species dataset

- [x] Regions of Floristic Endemism in Southern Africa

- [x]  frog coverage density

- [x] frog species richness

- [ ] Limpopo Protected Area Expansion Strategy Focus Areas / Focus regions

- [ ] Waterberg District Municipality Bioregional Plan

- [x] Communities - villages

- [ ] land use plans

- [x] previous homelands

SWSA 2017 version uploaded and invalid geometries have been fixed.

**Comment by seabilwe** [comment]
@zacharlie I have added some datasets on the list, but I have not assigned any key to them...

**Comment by gubuntu** [comment]
@seabilwe simply add those to the catalog, this doesn't need a GH issue (and the keys are not important at this stage)

Cleaning the catalogue means populating it properly and updating the status of each data set

**Comment by seabilwe** [comment]
Some of the data from this list has been acquired.

I am closing this issue

**Comment by gubuntu** [comment]
It should show the final location of all the layers we acquired and used and have a column indicating if we didn't use it. This is the final reference list so it should be up to date and accurate
