### ISSUE TITLE
Map 2 for milestone 4 report

### ISSUE THREAD

**Issue by seabilwe** [kartoza/WBR-SEMP#28]
- [x] main layer: 2019 Vegmap
- [x] contextual overlays (just boundaries)
  - WDC boundary
  - IBA boundary
  - WBR boundary
  - Quaternary catchment boundaries
  - study area / AOI from #24

**Comment by seabilwe** [comment]
@gubuntu  I used the vegetation layer from 2012, the current one has empty rows each, I uploaded it to the schema but still gave me the same results...I have asked Charlie to assist and upload it. At the moments I will use the 2012 and as soon as 2018 on is uploaded I will use that. But nothing has changed when comparing the 2018 and 2012 versions:

I classified the map into bioregion and then the types of vegetation there
**Bioregions:**
![image](https://user-images.githubusercontent.com/56301949/91809423-14827980-ec2d-11ea-93b6-8e2418dd82b5.png)

Type with area
![image](https://user-images.githubusercontent.com/56301949/91811203-6c21e480-ec2f-11ea-833e-2029bf246044.png)

**Comment by seabilwe** [comment]
I also tried to remove the vegetation types outside the boundary but failed to do so

**Comment by gubuntu** [comment]
you can mask them and then when Richard agrees on the the boundary, clip them to get correct areas

**Comment by gubuntu** [comment]
never style a categorical data set with a continous colour range

Vegmap has a standard legend that should be in PostGIS as a default style or in GeoServer

**Comment by seabilwe** [comment]
Alright got it

**Comment by seabilwe** [comment]
@gubuntu 

![report 5](https://user-images.githubusercontent.com/56301949/91944214-02bcd700-ecfe-11ea-83d6-c48cba4d27ff.JPG)

**Comment by gubuntu** [comment]
- where are the rest of the colours?
- needs to be in a layout with a legend etc.
- the layout needs a table showing the area of each vegetation type in the AOI
