### ISSUE TITLE
4.1 Describe the ecological mosaic

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#44]
4.1 "Encompass a mosaic of ecological systems representative of major biogeographic region(s), including a gradation of human interventions".
(The term "major biogeographic region" is not strictly defined but it would be useful to refer to the Udvardy classification system (http://www.unep-wcmc.org/udvardys-biogeographical-provinces-1975_745.html)).

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by zacharlie** [comment]
The Waterberg Biosphere Reserve lies within the South African Woodland/Savanna biogeographical province (udvardy), as described in #49

The following map and text is an extract from Low & Rebelo (1996) for Savanna Biome, taken from the SANBI website http://pza.sanbi.org/vegetation/savanna-biome

![image](https://user-images.githubusercontent.com/64078329/100727994-a423f980-33cf-11eb-93e8-0650f5ee502b.png)

> The Savanna Biome is the largest Biome in southern Africa, occupying 46% of its area, and over one-third the area of South Africa. It is well developed over the lowveld and Kalahari region of South Africa and is also the dominant vegetation in Botswana, Namibia and Zimbabwe. It is characterized by a grassy ground layer and a distinct upper layer of woody plants. Where this upper layer is near the ground the vegetation may be referred to as Shrubveld, where it is dense as Woodland, and the intermediate stages are locally known as Bushveld.
> 
> The environmental factors delimiting the biome are complex: altitude ranges from sea level to 2 000 m; rainfall varies from 235 to 1 000 mm per year; frost may occur from 0 to 120 days per year; and almost every major geological and soil type occurs within the biome. A major factor delimiting the biome is the lack of sufficient rainfall which prevents the upper layer from dominating, coupled with fires and grazing, which keep the grass layer dominant. Summer rainfall is essential for the grass dominance, which, with its fine material, fuels near-annual fires. In fact, almost all species are adapted to survive fires, usually with less than 10% of plants, both in the grass and tree layer, killed by fire. Even with severe burning, most species can resprout from the stem bases.
> 
> The grass layer is dominated by C 4-type grasses, which are at an advantage where the growing season is hot, but where rainfall has a stronger winter component, C 3-type grasses dominate. The shrub-tree layer may vary from 1 to 20 m in height, but in Bushveld typically varies from 3 to 7 m. The shrub-tree element may come to dominate the vegetation in areas which are being overgrazed.
> 
> Most of the savanna vegetation types are used for grazing, mainly by cattle or game. In the southernmost savanna types, goats are the major stock. In some types crops and subtropical fruit are cultivated. These mainly include the Clay Thorn Bushveld (14), parts of Mixed Bushveld (18), and Sweet Lowveld Bushveld (21). Urbanization is not a problem, perhaps because the hot, moist climate and diseases (sleeping sickness, malaria) hindered urban development.
> 
> Conservation of savanna is good in principle, mainly due to the presence of the Kruger and Kalahari Gemsbok National Parks within the biome. Similarly, in neighbouring countries, large reserves occur, such as Etosha, Gemsbok, Chobe and Hwange National Parks and the Central Kalahari Game Reserve. However, this high area conserved in South Africa, belies the fact that half of savanna vegetation types are inadequately conserved, in having less than 5% of their area in reserves. However, much of the area is used for game-farming and can thus be considered effectively preserved, provided that sustainable stocking levels are maintained. The importance of tourism and big game hunting in the conservation of the area must not be underestimated.

The following excerpt from the Waterberg District Bioregional Plan further describes the particular ecosystems found in the region.

> 2.4 Vegetation and Threatened Ecosystems
> 
> The Waterberg District supports predominantly savanna vegetation, with some grassland and forest (see Table 2). Small patches of azonal vegetation types associated with hydrological processes, geology and salinity occur along wetlands and rivers, such as the Nyl, Crocodile, Tamboti and Moloko. There are 20 South African vegetation types in the Waterberg District (Mucina and Rutherford, 2006) (Figure 2).

The Waterberg disctrict is of distinct ecological importance for a variety of reasons, which are well described in the Waterberg District Bioregional Plan within Section 2 - Part B: Biodiversity Profile

A number of Important Biodiversity Features in the Waterberg District are described, including some of the following features:

- Waterberg Mountain Complex ecosystem services
- Nylsvley Nature Reserve and the Nyl floodplain RAMSAR site
- The Pienaars (Moretele) River and floodplain, which is of ecological importance but has no formal protection or conservation status
- Multiple river systems, especially those that are in a natural or near-natural ecological state, including the The Limpopo, Mogalakwena and Mokolo rivers which support sensitive species
- Important Bird Areas (IBAs) - Northern Turf Thornveld, Waterberg System, Nyl River Floodplain, which face threats from some of the following elements:
   - mining
   - uncontrolled fires
   - vulture poisoning
   - infrastructure collisions
   - cultivated land loss
   - flow impact

**Comment by gubuntu** [comment]
nice work @zacharlie

**Comment by gubuntu** [comment]
Biomes according to Rutherford and Mucina 2021 (savannah, grassland and azonal)
<img width="801" alt="Screenshot 2022-10-30 at 15 05 14" src="https://user-images.githubusercontent.com/496911/200108361-7cf1a9f0-9b53-4135-815a-92dbab692692.png">
