### ISSUE TITLE
4.2 Describe significance to conservation of biodiversity

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#45]
4.2 "Be of significance for biological diversity conservation".
(This should refer not only to the numbers of endemic or rare species, but may also refer to species on the IUCN Red List or CITES appendices, at the local, regional or global levels, and also to species of global importance, rare habitat types or habitats with unique land use practices (for example traditional grazing or artisanal fishing) favouring the conservation of biological diversity).

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by zacharlie** [comment]
The region is important to many endemic and sensitive species of various types, as indicated in the species list summaries (#60).

A full description of the regional ecology is outlined in #44

The following excerpt from the Waterberg District Bioregional Plan summarises the key significance of the region for biodiversity conservation.


> 2.1 Significance of the Biodiversity within the Waterberg District
> 
> The Waterberg District supports unique vegetation types on the central mountainous areas, which show floristic gradients similar to the Soutpansberg, the Sekhukhuneland and the Wolkberg Centres of Endemism. This has resulted in most of the region being covered by vegetation types that are endemic and near-endemic to the Waterberg District Municipality, as well as a range of species endemic to the region.
> 
> Twenty-two threatened plant species occur within the Waterberg District, of which three species are listed as Critically Endangered, three as Endangered, and 16 as Vulnerable. The Waterberg
> District is also home to 45 mammal species of special concern, of which 15 are classified as Critically Endangered, Endangered or Vulnerable. Three Important Bird Areas are defined in the Waterberg region representing 21 threatened bird species inhabiting the region.

There are also many critical biodiversity areas, as outlined in the [Waterberg District Bioregional Plan](http://bgis.sanbi.org/Document/Download?id=2181) and the National Biodiversity Assessment data outlined in the conervation functions (#54).

**Comment by gubuntu** [comment]
thanks @zacharlie
