### ISSUE TITLE
4.4 and 4.5 Develop and describe outer boundary and zones

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#46]
- [ ] 4.4 "Have an appropriate size to serve the three functions of biosphere reserves"
(This refers more particularly to (a) the surface area required to meet the long term conservation objectives of the core area(s) and the buffer zone(s) and (b) the availability of areas suitable for working with local communities in testing and demonstrating sustainable uses of natural resources).

4.5 Through appropriate zonation :
- [ ] "(a) a legally constituted core area or areas devoted to long term protection, according to the conservation objectives of the biosphere reserve, and of sufficient size to meet these objectives". (Describe the core area(s) briefly, indicating their legal status, their size, the main conservation objectives).

- [ ] "(b) a buffer zone or zones clearly identified and surrounding or contiguous to the core area or areas, where only activities compatible with the conservation objectives can take place".
(Describe briefly the buffer zones(s), their legal status, their size, and the activities which are ongoing and planned there).

- [ ] "(c) an outer transition area where sustainable resource management practices are promoted and developed".
(The Seville Strategy gave increased emphasis to the transition area since this is the area where the key issues on environment and development of a given region are to be addressed. Describe briefly the transition area(s), the types of questions to be addressed there in the near and the longer terms. The Madrid Action Plan states that the outer boundary should be defined through stakeholder consultation).

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by gubuntu** [comment]
#4.4 update Nov 22

Latest version of proposed extension:

"buffer" "321022ha" "973057ha"
"core" "321022ha" "1601399ha"
"transition" "321022ha" "635766ha"

**Comment by gubuntu** [comment]
# 4.5a update Nov 22

These are the reserves use to define the core areas. Note there are some duplicates arising from different names, consolidations etc. The maps shows these with darker shades of brown indicating more overlaps.

<img width="1057" alt="Screenshot 2022-11-05 at 11 20 48" src="https://user-images.githubusercontent.com/496911/200112833-411452c7-d4e9-4492-a811-dfd9e74a95f8.png">

"name"	"area_ha"	"source"	"owner_or_type"
"91 Ammunisie Depo Private Nature Reserve"	3875	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Agen Landgoed Private Nature Reserve"	7485	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Alem Private Nature Reserve"	2731	"SANBI ""protected_areas"""	"Nature Reserve"
"Alexander Estate Private Nature Reserve"	2980	"SANBI ""protected_areas"""	"Nature Reserve"
"Alkantrant"	2076	"CBA"	"Private"
"Alkantrant Nature Reserve"	2084	"SANBI ""protected_areas"""	"Nature Reserve"
"Animalia Private Nature Reserve"	1285	"SANBI ""protected_areas"""	"Nature Reserve"
"Apieskraal Private Nature Reserve"	1040	"SANBI ""protected_areas"""	"Nature Reserve"
"Arzona Private Nature Reserve"	669	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Atherstone Nature Reserv"	23286	"CBA"	"LEDET"
"Atherstone Private Nature Reserve"	2421	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Atherstone Protected Natural Environment"	26353	"SANBI ""protected_areas"""	"Protected Environment"
"Austin Roberts Private Nature Reserve"	3428	"SANBI ""protected_areas"""	"Nature Reserve"
"Beesland Private Nature Reserve"	670	"SANBI ""protected_areas"""	"Nature Reserve"
"Belanie Private Nature Reserve"	1640	"SANBI ""protected_areas"""	"Nature Reserve"
"Bellevue"	5205	"CBA"	"Private"
"Ben Alberts"	2913	"CBA"	"Private"
"Benita Private Nature Reserve"	2298	"SANBI ""protected_areas"""	"Nature Reserve"
"B. J. Welgemoed Private Nature Reserve"	1664	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Blakleney"	3560	"CBA"	"Private"
"Blesbok Private Nature Reserve"	3042	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Blousloot Private Nature Reserve"	854	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Bokkiespan Private Nature Reserve"	1062	"SANBI ""protected_areas"""	"Nature Reserve"
"Bottero's Private Nature Reserve"	496	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Buffalo Springs Private Nature Reserve"	2780	"SANBI ""protected_areas"""	"Nature Reserve"
"Buffelsfontein Private Nature Reserve"	5928	"SANBI ""protected_areas"""	"Nature Reserve"
"Buffelsvlei Private Nature Reserve"	1381	"SANBI ""protected_areas"""	"Nature Reserve"
"Chriwilma Private Nature Reserve"	1303	"SANBI ""protected_areas"""	"Nature Reserve"
"Cilliers Broers Private Nature Reserve"	1921	"SANBI ""protected_areas"""	"Nature Reserve"
"Conservation Game Reserves Block"	19934	"CBA"	"Private"
"Contento Private Nature Reserve"	2118	"SANBI ""protected_areas"""	"Nature Reserve"
"C. R. Welgemoed Private Nature Reserve"	863	"SANBI ""protected_areas"""	"Nature Reserve"
"Danie Malan Private Nature Reserve"	850	"SANBI ""protected_areas"""	"Nature Reserve"
"Danie Steenkamp Private Nature Reserve"	1139	"SANBI ""protected_areas"""	"Nature Reserve"
"De Bruins Private Nature Reserve"	1235	"SANBI ""protected_areas"""	"Nature Reserve"
"De Draai"	1387	"CBA"	"Private"
"Deellam Private Nature Reserve"	1660	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Die Kraal Private Nature Reserve"	2907	"SANBI ""protected_areas"""	"Nature Reserve"
"Dnyala"	7977	"CBA"	"LEDET"
"D'nyala Nature Reserve"	8108	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Doelen Private Nature Reserve"	398	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Doorndraai Dam"	6847	"CBA"	"LEDET"
"Doorndraai Nature Reserve"	8570	"CBA"	"Private"
"Doornlaagte Private Nature Reserve"	2984	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Draaispruit Private Nature Reserve"	1466	"SANBI ""protected_areas"""	"Nature Reserve"
"Du Plessis No 1 Private Nature Reserve"	5077	"SANBI ""protected_areas"""	"Nature Reserve"
"Du Plessis No 2 Private Nature Reserve"	3335	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Duplo Private Nature Reserve"	1492	"SANBI ""protected_areas"""	"Nature Reserve"
"Durand Private Nature Reserve"	1093	"SANBI ""protected_areas"""	"Nature Reserve"
"E. A. Faber Private Nature Reserve"	1681	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Eaglestone Private Nature Reserve"	7174	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"E. H. Rachmann Private Nature Reserve"	937	"SANBI ""protected_areas"""	"Nature Reserve"
"Elandsberg Nature Reserve"	17937	"CBA"	"Private"
"Elandsberg Private Nature Reserve"	1136	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Elandskloof Private Nature Reserve"	2355	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Els Private Nature Reserve"	1176	"SANBI ""protected_areas"""	"Nature Reserve"
"Entabeni"	19698	"CBA"	"Private"
"Entabeni Nature Reserve"	12052	"CBA"	"DAFF"
"Erasmus Private Nature Reserve"	1297	"SANBI ""protected_areas"""	"Nature Reserve"
"Fairfield Private Nature Reserve"	986	"SANBI ""protected_areas"""	"Nature Reserve"
"Fairlawn Private Nature Reserve"	1767	"SANBI ""protected_areas"""	"Nature Reserve"
"Familie Private Nature Reserve"	664	"SANBI ""protected_areas"""	"Nature Reserve"
"Fossil Hominid Sites of SA: Makapan Valley(Buffer)"	48086	"SANBI ""protected_areas"""	"World Heritage Site"
"Fossil Hominid Sites of SA: Makapan Valley(Core)"	2215	"SANBI ""protected_areas"""	"World Heritage Site"
"Geelhoutkop Private Nature Reserve"	475	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Geluk Private Nature Reserve"	2878	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Gelukshoek Private Nature Reserve"	895	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Glenesk Private Nature Reserve"	1515	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Goetsch Bros Private Nature Reserve"	910	"SANBI ""protected_areas"""	"Nature Reserve"
"G.O.W. Klause Private Nature Reserve"	1404	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Groenfontein Private Nature Reserve"	565	"SANBI ""protected_areas"""	"Nature Reserve"
"Grootvalley Protected Environment"	506	"SANBI ""protected_areas"""	"Protected Environment"
"Gryshemp Private Nature Reserve"	526	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Gys Vlok Nature Reserve"	1109	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Haakdoorn Private Nature Reserve"	1219	"SANBI ""protected_areas"""	"Nature Reserve"
"Hallam Private Nature Reserve"	1864	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Hanover Private Nature Reserve"	2421	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Hartbees Private Nature Reserve"	876	"SANBI ""protected_areas"""	"Nature Reserve"
"Hartley Private Nature Reserve"	1688	"SANBI ""protected_areas"""	"Nature Reserve"
"Helena Private Nature Reserve"	568	"SANBI ""protected_areas"""	"Nature Reserve"
"Hen Nel Private Nature Reserve"	4774	"SANBI ""protected_areas"""	"Nature Reserve"
"Hermia Private Nature Reserve"	2433	"SANBI ""protected_areas"""	"Nature Reserve"
"Hern House Private Nature Reserve"	1905	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Hetbad Nature Reserve"	700	"CBA"	"Ex MPTA to be transferred to LEDET"
"H. L. Crause Private Nature Reserve"	1630	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Hoekberge Private Nature Reserve"	3252	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Hou Moed Private Nature Reserve"	782	"SANBI ""protected_areas"""	"Nature Reserve"
"HUWI iii Private Nature Reserve"	2497	"SANBI ""protected_areas"""	"Nature Reserve"
"HUWI ii Private Nature Reserve"	3720	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"HUWI i Private Nature Reserve"	10690	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Innes Mellet Private Nature Reserve"	2377	"SANBI ""protected_areas"""	"Nature Reserve"
"Jacob van der Merwe Private Nature Reserve"	705	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Jan Kloppers Private Nature Reserve"	1103	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"J. C. R. Pretorius Private Nature Reserve"	2371	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Jembisa"	5047	"CBA"	"Private"
"J. G. Erasmus Private Nature Reserve"	1761	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"J. L. Moerdyk Gedenk Private Nature Reserve"	1650	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Jobedi"	5181	"CBA"	"Private"
"Joe Sunich"	4402	"CBA"	"Private"
"Ka'ingo Nature Reserve"	9211	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Ka'Lngo & Mokolo Private Nature Reserve"	12767	"CBA"	"Private"
"Karel Coetzee Private Nature Reserve"	1515	"SANBI ""protected_areas"""	"Nature Reserve"
"Keta Farms"	10368	"CBA"	"Private"
"Kindjie Private Nature Reserve"	1259	"SANBI ""protected_areas"""	"Nature Reserve"
"Knob's Valley Private Nature Reserve"	3718	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Knopieskop Private Nature Reserve"	2171	"SANBI ""protected_areas"""	"Nature Reserve"
"Koedoeskop Private Nature Reserve"	848	"SANBI ""protected_areas"""	"Nature Reserve"
"Koerooi Private Nature Reserve"	2544	"SANBI ""protected_areas"""	"Nature Reserve"
"Kokkeder Private Nature Reserve"	2899	"SANBI ""protected_areas"""	"Nature Reserve"
"Korvanleo Private Nature Reserve"	1972	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Kranskoppie Nature Reserve"	6242	"CBA"	"Private"
"Kranskop Private Nature Reserve"	3768	"SANBI ""protected_areas"""	"Nature Reserve"
"Kroondal Private Nature Reserve"	1796	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Kroon Welgemoed Private Nature Reserve"	1699	"SANBI ""protected_areas"""	"Nature Reserve"
"Krupel Private Nature Reserve"	1471	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Kwalata Game Reserve"	21680	"CBA"	"Private"
"Lapalala Nature Reserve"	37178	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Lapalala Wilderness"	32010	"CBA"	"Private"
"Leana Nature Reserve"	517	"SANBI ""protected_areas"""	"Nature Reserve"
"Leeuwkopje Private Nature Reserve"	987	"SANBI ""protected_areas"""	"Nature Reserve"
"Leopard Cave Safaris Private Nature Reserve"	4038	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Leopard's Hill Private Nature Reserve"	1028	"SANBI ""protected_areas"""	"Nature Reserve"
"Les Brown Private Nature Reserve"	1354	"SANBI ""protected_areas"""	"Nature Reserve"
"Limpopo Central Bushveld"	1634	"NPAES"	"planned"
"Limpopo Central Bushveld"	2518	"NPAES"	"planned"
"Limpopo Central Bushveld"	2279	"NPAES"	"planned"
"Limpopo Central Bushveld"	951	"NPAES"	"planned"
"Limpopo Central Bushveld"	2726	"NPAES"	"planned"
"Limpopo Central Bushveld"	1055	"NPAES"	"planned"
"Limpopo Central Bushveld"	9016	"NPAES"	"planned"
"Limpopo Central Bushveld"	10608	"NPAES"	"planned"
"Limpopo Central Bushveld"	10294	"NPAES"	"planned"
"Limpopo Central Bushveld"	585	"NPAES"	"planned"
"Limpopo Central Bushveld"	587	"NPAES"	"planned"
"Limpopo Central Bushveld"	956	"NPAES"	"planned"
"Limpopo Central Bushveld"	8291	"NPAES"	"planned"
"Limpopo Central Bushveld"	829	"NPAES"	"planned"
"Limpopo Central Bushveld"	1280	"NPAES"	"planned"
"Limpopo Central Bushveld"	3929	"NPAES"	"planned"
"Limpopo Central Bushveld"	33123	"NPAES"	"planned"
"Limpopo Central Bushveld"	8306	"NPAES"	"planned"
"Limpopo Central Bushveld"	770	"NPAES"	"planned"
"Limpopo Central Bushveld"	2060	"NPAES"	"planned"
"Lindani"	2810	"CBA"	"Private"
"L. Meyburgh Private Nature Reserve"	2431	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Louis Kotze Private Nature Reserve"	5007	"SANBI ""protected_areas"""	"Nature Reserve"
"Lushof Private Nature Reserve"	868	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Madeleine Robinson"	1858	"CBA"	"Private"
"Mama Tau"	2851	"CBA"	"Private"
"Marakele National Park"	64632	"CBA"	"South African National Parks"
"Mara Private Nature Reserve"	749	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Maricostroom Private Nature Reserve"	1574	"SANBI ""protected_areas"""	"Nature Reserve"
"Masebe"	4400	"CBA"	"LEDET"
"Matlabas Private Nature Reserve"	1074	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Meletse Game Reserve"	13100	"CBA"	"Private"
"Minnaar Private Nature Reserve"	1622	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"M.M. Schoenfeld Private Nature Reserve"	1469	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Moepel"	24300	"CBA"	"Private"
"Moepel Private Nature Reserve"	2265	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Mogol Dam"	5125	"CBA"	"LEDET"
"Mogol Nature Reserve"	5255	"SANBI ""protected_areas"""	"Nature Reserve"
"Mogoto Private Nature Reserve"	6595	"SANBI ""protected_areas"""	"Nature Reserve"
"Mokolo Nature Reserve"	8065	"SANBI ""protected_areas"""	"Nature Reserve"
"Mooikloof Private Nature Reserve"	360	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Mosdene Private Nature Reserve"	4959	"CBA"	"Private"
"Mowbray Private Nature Reserve"	733	"SANBI ""protected_areas"""	"Nature Reserve"
"Naboom Private Nature Reserve"	4672	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Next Door Private Nature Reserve"	810	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Nico Private Nature Reserve"	10197	"SANBI ""protected_areas"""	"Nature Reserve"
"Nungu Private Nature Reserve"	6066	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Nungu Protected Environment"	2761	"DEFF ""sapad_or_2020_q1"""	"Protected Environment"
"NW/Gauteng Bushveld"	9565	"NPAES"	"planned"
"Nyl River Floodplain"	24292	"CBA"	"Private"
"Nylsvlei + Vogelfontein"	3981	"CBA"	"LEDET"
"Nylsvley Private Nature Reserve"	3090	"SANBI ""protected_areas"""	"Nature Reserve"
"Nyl Valley Private Nature Reserve"	2593	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Olifantsdrif Private Nature Reserve"	4906	"SANBI ""protected_areas"""	"Nature Reserve"
"Olifantskop Private Nature Reserve"	446	"SANBI ""protected_areas"""	"Nature Reserve"
"Ons Toekoms Private Nature Reserve"	2853	"SANBI ""protected_areas"""	"Nature Reserve"
"Paarl Private Nature Reserve"	1171	"SANBI ""protected_areas"""	"Nature Reserve"
"Palala Private Nature Reserve"	7216	"SANBI ""protected_areas"""	"Nature Reserve"
"Palmer Private Nature Reserve"	4692	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Parkveld Private Nature Reserve"	3020	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Pat Cloete Private Nature Reserve"	2908	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Patrysbos Private Nature Reserve"	4663	"SANBI ""protected_areas"""	"Nature Reserve"
"Pearson Private Nature Reserve"	3322	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Percy Fyfe"	2948	"CBA"	"LEDET"
"Percy Fyfe Nature Reserve"	2986	"SANBI ""protected_areas"""	"Nature Reserve"
"Philip Wulfsohn Private Nature Reserve"	772	"SANBI ""protected_areas"""	"Nature Reserve"
"Phillippus Private Nature Reserve"	936	"SANBI ""protected_areas"""	"Nature Reserve"
"Pierre Fourie Private Nature Reserve"	3055	"SANBI ""protected_areas"""	"Nature Reserve"
"Republiek Private Nature Reserve"	1261	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Retiefs Private Nature Reserve"	4662	"SANBI ""protected_areas"""	"Nature Reserve"
"Rhinoland"	6600	"CBA"	"Private"
"Rietfontein Private Nature Reserve"	371	"SANBI ""protected_areas"""	"Nature Reserve"
"Rinda Private Nature Reserve"	2917	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Rissik Private Nature Reserve"	2889	"SANBI ""protected_areas"""	"Nature Reserve"
"Robco Private Nature Reserve"	3082	"SANBI ""protected_areas"""	"Nature Reserve"
"Roets Private Nature Reserve"	2976	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Rooiberg Private Nature Reserve"	5796	"SANBI ""protected_areas"""	"Nature Reserve"
"Rousseau Snyman Private Nature Reserve"	3106	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Ruskamp Private Nature Reserve"	766	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Rustenburg Platinum Mines (Union Section) Private Nature Reserve"	1483	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Saamloop Private Nature Reserve"	4068	"SANBI ""protected_areas"""	"Nature Reserve"
"Safari No 1 Private Nature Reserve"	4861	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Safari No 2 Private Nature Reserve"	2585	"SANBI ""protected_areas"""	"Nature Reserve"
"Shambala Game Reserve"	16420	"CBA"	"Private"
"Sharme Private Nature Reserve"	2179	"SANBI ""protected_areas"""	"Nature Reserve"
"Sheleni Game Reserve"	10871	"CBA"	"Private"
"Shewebeswebe"	5026	"CBA"	"Private"
"Somerset Private Nature Reserve"	7493	"SANBI ""protected_areas"""	"Nature Reserve"
"Sondersorge Nature Reserve"	412	"SANBI ""protected_areas"""	"Nature Reserve"
"Spoorsny Private Nature Reserve"	2018	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Sporting Chance Private Nature Reserve"	1233	"SANBI ""protected_areas"""	"Nature Reserve"
"Spruytskloof Private Nature Reserve"	1204	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Swebeswebe Nature Reserve"	4926	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Thaba Tholo Eco Park"	34277	"CBA"	"Private"
"Thabazimbi Private Nature Reserve"	2569	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Tierschutz Private Nature Reserve"	3319	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Timbewaar Private Nature Reserve"	1990	"SANBI ""protected_areas"""	"Nature Reserve"
"Tortoiseshell Private Nature Reserve"	1847	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Touchstone"	17315	"CBA"	"Private"
"Tweeling Private Nature Reserve"	1476	"SANBI ""protected_areas"""	"Nature Reserve"
"Unknown Conservation Area"	9168	"CBA"	"Private"
"Van Heerden Private Nature Reserve"	683	"SANBI ""protected_areas"""	"Nature Reserve"
"Van Wyk's Private Nature Reserve"	4512	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Vrug-op-arbeid Nature Reserve"	1235	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Vyeboom Private Nature Reserve"	753	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Wag-'n-Bietjie No.1 Private Nature Reserve"	913	"SANBI ""protected_areas"""	"Nature Reserve"
"Wag-'n-Bietjie No.2 Private Nature Reserve"	384	"SANBI ""protected_areas"""	"Nature Reserve"
"Waterval Game Reserve"	3428	"SANBI ""protected_areas"""	"Nature Reserve"
"Webtex Estates Private Nature Reserve"	1524	"SANBI ""protected_areas"""	"Nature Reserve"
"Welgevonden Game Reserve"	41093	"CBA"	"Private"
"Wellington Private Nature Reserve"	516	"SANBI ""protected_areas"""	"Nature Reserve"
"Weltevrede Private Nature Reserve"	17270	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Witvinger Nature Reserve"	4503	"CBA"	"LEDET"
"Witwater"	1381	"CBA"	"Private"
"Wonderkop"	14472	"CBA"	"LEDET"
"Wonderkop Nature Reserve"	13250	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Woodhope Private Nature Reserve"	1698	"SANBI ""protected_areas"""	"Nature Reserve"
"W Ranch Private Nature Reserve"	2076	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Wyn Van Staden Private Nature Reserve"	1236	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Youngs Private Nature Reserve"	2649	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"
"Zwartkloof Private Nature Reserve"	484	"DEFF ""sapad_or_2020_q1"""	"Nature Reserve"

**Comment by gubuntu** [comment]
# 4.5b update Nov 2022

The Land cover / land use class from NLC 2018 that composes the majority of a property was assigned to the farm portions as a proxy for 'ongoing activities'. Too much data to include here. See Issue46.sql and 'landcover on farms.sql'

# 4.5c update Nov 2022
as for 4.4b

**Comment by seabilwe** [comment]
@gubuntu 

**Dataset Title: Protected areas**
Data Origin: South African National Biodiversity Institute

**Dataset Title: South African Protected Areas Database (SAPAD_OR_2020_Q1)**
Dataset Reference Date: 2020/06/04
Dataset Responsible Party: Department of Environmental Affairs / Director Enterprise Geospatial Information Management

**Dataset Title: National Protected Area Expansion Strategy**
Data Origin: SANPARKS/SANBI
Capture Source: Conservation planning output of the National Protected Areas Expansion Strategy, last updated June 2010

**Dataset Title: Critical Biodiversity Areas**
Data Origin: Limpopo Conservation Plan version 2 (2013)
Capture Source: Limpopo Conservation Plan version 2 (2013)
Source:  Limpopo Department of Economic Development &Amp; Tourism (LEDET) 2013
