### ISSUE TITLE
6. describe location

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#47]
6. LOCATION (COORDINATES AND MAP(S)):
6.1 Provide the biosphere reserve’s standard geographical coordinates (all projected under WGS 84):

Cardinal points:|Latitude  |       Longitude
-|-|-
Most central point: ||
Northernmost point: ||
Southernmost point: ||
Westernmost point:||
 Easternmost point:||

6.2 Provide a map(s) on a topographic layer of the precise location and delimitation of the three zones of the biosphere reserve (Map(s) shall be provided in both paper and electronic copies). Shapefiles (also in WGS 84 projection system) used to produce the map must be attached to the electronic copy of the form.

If possible, also provide a link to access this map on the internet (e.g. Google map, website...).

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by NyakudyaA** [comment]
@gubuntu Do we have color schemes we need to be using for the maps?
![zones-map](https://user-images.githubusercontent.com/2510900/97423404-d6958f00-1917-11eb-8611-4a4db7895ae1.png)

**Comment by gubuntu** [comment]
big overlap with #57, I think you or @seabilwe should do both

I used colours from the SANBI ArcGIS FS of the current zones

**Comment by NyakudyaA** [comment]
I am trying to get the points using the following link https://gis.stackexchange.com/questions/323289/how-to-calculate-extreme-point-most-north-or-east-etc-of-geographypolygon-ty

![pnts](https://user-images.githubusercontent.com/2510900/97693746-49367400-1aaa-11eb-8fd6-773245b56fee.png)

If I use the `st_touches` between the envelope and the wbr geometry I always get false. Any hints here @gubuntu 

```
select b.id, from  wbr_boundary_new b
where 
st_touches ( b.geom, 
(select st_orientedenvelope(st_multi(st_union(geom))) as geom  from wbr_boundary_new)) = 'true'
```

If I create the points manually it looks like
![points](https://user-images.githubusercontent.com/2510900/97699038-2f992a80-1ab2-11eb-87b4-b3026425fcfc.png)

**Comment by zacharlie** [comment]
Cardinal points:|Latitude|Longitude
-|-|-
Most central point: |-24.20834727|28.10626394
Northernmost point: |-22.9974814|27.950504
Southernmost point: |-25.138986|27.226122
Westernmost point:|-24.1288396|29.292768
Easternmost point:|-24.649593|26.340858

I used the "minimum bounding geometries" tool from QGIS with the convex hull function as described in #57 

Using the "Convex Hull" Layer, I sorted the table by latitude and longitude to obtain the minimum and maximum positions. I dissolved the areas,reprojected to EPSG:4326 and generated a central point using the "centroids" QGIS tool and added Lat/Long ($x,$y) fields to obtain the center position

![result](https://user-images.githubusercontent.com/64078329/101135543-9f9c5280-3614-11eb-8f7d-5f2afdf6253f.png)

I believe the map produced for #57 should also cover the cartographic requirements for this. The public URL for the map image is `https://user-images.githubusercontent.com/64078329/101136140-919b0180-3615-11eb-81a4-e4977971c87b.png`

**Comment by gubuntu** [comment]
thanks @zacharlie and @NyakudyaA
