### ISSUE TITLE
8. describe biogeographical region

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#49]
8. BIOGEOGRAPHICAL REGION:
[Indicate the generally accepted name of the biogeographical region in which the proposed biosphere reserve is located.] (The term "major biogeographic region" is not strictly defined but you may wish to refer to the Udvardy classification system (http://www.unep-wcmc.org/udvardys-biogeographical-provinces-1975_745.html)).

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by zacharlie** [comment]
The GIS Data available from https://www.unep-wcmc.org/resources-and-data/udvardys-biogeographical-provinces is only available under a Non-Commercial License, and the listed data services are unavailable.

The original paper is, however, available for download online from the [](https://web.archive.org/web/20110811210836/http://cmsdata.iucn.org/downloads/udvardy.pdf) or the [iucn library](https://portals.iucn.org/library/sites/library/files/documents/OP-018.pdf).

The Waterberg Biosphere is located within the **South African Woodland/Savanna** biogeographical province (udvardy). This region is of the _Tropical dry forests / Woodlands_ biome type within the _Africotropical_ realm.

Additional details on the regional biogeography is available from #44

List of biogeographic provinces available on [wikipedia](https://en.wikipedia.org/wiki/List_of_biogeographic_provinces).

**Comment by gubuntu** [comment]
thanks @zacharlie
