### ISSUE TITLE
10. describe the human population

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#51]
- [x] 10. HUMAN POPULATION OF PROPOSED BIOSPHERE RESERVE:
[Approximate number of people living within the proposed biosphere reserve]
permanently / seasonally

Zone | permanently | seasonally
-|-|-
10.1 Core Area(s)||
10.2 Buffer Zone(s):||
10.3 Transition Area(s): ||
total||

- [x] 10.4 Brief description of local communities living within or near the proposed biosphere reserve. (Indicate ethnic origin and composition, minorities etc., main economic activities (e.g. pastoralism, tourism) and the location of their main areas of concentration, with reference to the map (section 6.2)).
- [ ] 10.5 Name(s) of the major settlement(s) within and near the proposed biosphere reserve with
reference to the map (section 6.2):
- [ ] 10.6. Cultural significance:
(Briefly describe the proposed biosphere reserve's importance in terms of past and current cultural values (religious, historical, political, social, ethnological) and others, if possible with distinction between material and intangible heritage (c.f. UNESCO Convention concerning the Protection of the World Cultural and Natural Heritage 1972 and UNESCO Convention for the Safeguard of the Intangible Cultural Heritage 2003 (http://portal.unesco.org/en/ev.php-URL_ID=13055&URL_DO=DO_TOPIC&URL_SECTION=201.html and http://portal.unesco.org/en/ev.php-URL_ID=17716&URL_DO=DO_TOPIC&URL_SECTION=201.html)).
- [x] 10.7 Specify the number of spoken and written languages (including ethnic, minority and endangered languages) in the biosphere reserve.
(Refer, for instance, to the UNESCO Atlas of Endangered languages (http://www.unesco.org/culture/languages- atlas/index.php)).

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by NyakudyaA** [comment]
>     * [ ]  10. HUMAN POPULATION OF PROPOSED BIOSPHERE RESERVE:
>       [Approximate number of people living within the proposed biosphere reserve]
>       permanently / seasonally
> 
> 
> Zone 	permanently 	seasonally
> 10.1 Core Area(s) 		
> 10.2 Buffer Zone(s): 		
> 10.3 Transition Area(s): 		
> total 		
> 
>     * [ ]  10.4 Brief description of local communities living within or near the proposed biosphere reserve. (Indicate ethnic origin and composition, minorities etc., main economic activities (e.g. pastoralism, tourism) and the location of their main areas of concentration, with reference to the map (section 6.2)).

![zones-stats](https://user-images.githubusercontent.com/2510900/97271502-4e40bc80-1839-11eb-9dce-359a035d34cc.png)

Is section 6.2 is from holness ?
> 
>     * [ ]  10.5 Name(s) of the major settlement(s) within and near the proposed biosphere reserve with
>       reference to the map (section 6.2):
> 
>     * [ ]  10.6. Cultural significance:
>       (Briefly describe the proposed biosphere reserve's importance in terms of past and current cultural values (religious, historical, political, social, ethnological) and others, if possible with distinction between material and intangible heritage (c.f. UNESCO Convention concerning the Protection of the World Cultural and Natural Heritage 1972 and UNESCO Convention for the Safeguard of the Intangible Cultural Heritage 2003 (http://portal.unesco.org/en/ev.php- URL_ID=13055&URL_DO=DO_TOPIC&URL_SECTION=201.html and http://portal.unesco.org/en/ev.php- URL_ID=17716&URL_DO=DO_TOPIC&URL_SECTION=201.html)).
> 
>     * [ ]  10.7 Specify the number of spoken and written languages (including ethnic, minority and endangered languages) in the biosphere reserve.
>       (Refer, for instance, to the UNESCO Atlas of Endangered languages (http://www.unesco.org/culture/languages- atlas/index.php)).
> 
> 
> ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by zacharlie** [comment]
### 10.5 Name(s) of the major settlement(s) within and near the proposed biosphere reserve with
reference to the map (section 6.2):

The map provided (6.2) in #47 is currently expected to be the same as #57, which is `https://user-images.githubusercontent.com/64078329/101136140-919b0180-3615-11eb-81a4-e4977971c87b.png`.

The settlement names can be listed from the survey village layers and town names generated for cartographic purposes.

Town names

- Bochum
- Modimolle
- Siyabuswa
- Thabazimbi
- Mokopane
- Lephalale
- Groblersbrug
- Vaalwater
- Mookgophong
- Northam
- Bela bela

Survey Village names

- Martinique
- Shongoane 1
- Phahladira
- Otherworld
- Mookgopong
- Boschdraai
- Leseding
- Moshi
- Vienna
- Chere
- Melkrivier
- Kgopung
- Kabeana
- Dikgokgopheng
- Nkgori
- Mabetha
- Mohlakaneng
- Lesodi
- Vanwykspan
- Nyakelang
- Skrikfontein
- Moshuka
- Leyden
- Hermansdal
- Moepel
- Taueatswala
- Rhenosterfontein
- Regorogile Ext 8
- Regorogile Ext 4
- Rooiberg stone Mine
- Mmaletswai
- Abbotspoort
- Matladi
- Shongoane 2
- Marapong
- Alma
- GaHlako
- GaMonare
- GaRapadi
- Dipere
- Segole 2
- Segole 1
- Senita
- GaMathekga
- Uitspanning
- GaMalope
- Wydhoek
- GaMonene
- GaMolekwa
- Kromkloof
- GaMasipa
- Bokwidi
- Marulaneng
- Mabula
- Rantlakane
- Makekeng
- Kaditshwene
- Phatsane
- Mmamatlakala
- GaNkidikitlana
- Uitzicht
- Nong
- GaChokoe
- Drekson
- Merebere
- Driehoek
- Phagameng

### 10.6. Cultural significance:

I believe this has already been suitably covered with the available resources in #55 in section _15.6 Spiritual and cultural values and customary practices: (Provide an overview of values and practices, including cultural diversity)_

**Comment by gubuntu** [comment]
nice work @NyakudyaA and @zacharlie

**Comment by gubuntu** [comment]
# updates nov 2022

from FB population:
10.1: core: 23239
10.2: buffer: 234281
10.3: transition: 465102
