### ISSUE TITLE
11. describe the biophysical characteristics

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#52]
- [ ] 11. BIOPHYSICAL CHARACTERISTICS
- [x] 11.1. General description of site characteristics and topography of area:
(Briefly describe the major topographic features (wetlands, marshes, mountain ranges, dunes etc.) which most typically characterize the landscape of the area).
- 11.2 Altitudinal range
- [x] 11.2.1 Highest elevation above sea level: _____________ metres
- [x] 11.2.2 Lowest elevation above sea level: ______________ metres
- [x] 11.2.3 For coastal/marine areas, maximum depth below mean sea level: ____________ metres
- [x] 11.3. Climate:
(Briefly describe the climate of the area, you may wish to use the regional climate classification by Köppen as suggested by WMO (http://www.wmo.int/pages/themes/climate/understanding_climate.php)).
- [x] 11.3.1 Average temperature of the warmest month: __________ °C
- [x] 11.3.2 Average temperature of the coldest month: __________ °C
- [x] 11.3.3 Mean annual precipitation: ___________ mm, recorded at an elevation of ___________ metres
- [x] 11.3.4 Is there a meteorological station in or near the proposed biosphere reserve? If so, what is its name and location and how long has it been operating?
- [x] 11.4. Geology, geomorphology, soils:
(Briefly describe important formations and conditions, including bedrock geology, sedimentary deposits, and important soil types).
- [x] 11.5 Bioclimatic zone:
(Indicate the bioclimatic region in which the proposed biosphere reserve is located, refer to the table below and tick the appropriate box for each area of the biosphere reserve).

Areas|Average annual rainfall/mm|Penman Aridity index|(UNEP index) Aridity index|Core area(s)|Buffer  zone(s)|Transition area(s)
-|-|-|-|-|-|-
Hyper-arid|P<100| <0.05| <0.05|||
Arid|100-400|0.05-0.28|0.05-0.20|||
Semi-arid|400-600|0.28-0.43|0.21-0.50|||
Dry Sub-humid|600-800|0.43-0.60|0.51-0.65|||
Moist Sub-humid|800-1200|0.60-0.90|>0.65|||
Per-humid|P>1200|>0.90||||
  
Table 1: Aridity index resulting from the use of P/ETP
Mean annual precipitation (P)/mean annual potential evapotranspiration (ETP)
- [ ] 11.6 Biological characteristics:
List main habitat types (e.g. tropical evergreen forest, savanna woodland, alpine tundra, coral reef, kelp beds) and land cover types (e.g. residential areas, agricultural land, pastoral land, cultivated areas, rangeland).
 For each type, indicate:
- REGIONAL if the habitat or land cover type is widely distributed within the biogeographical region within which the proposed biosphere reserve is located, to assess the habitat's or land cover type's representativeness;
- LOCAL if the habitat or land cover type is of limited distribution within the proposed biosphere reserve, to assess the habitat's or land cover type's uniqueness.
For each habitat or land cover type, list characteristic species and describe important natural processes (e.g. tides, sedimentation, glacial retreat, natural fire) or human impacts (e.g. grazing, selective cutting, agricultural practices) affecting the system. As appropriate, refer to the vegetation or land cover map provided as supporting documentation.

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by seabilwe** [comment]
## 11. BIOPHYSICAL CHARACTERISTICS
### 11.1. General description of site characteristics and topography of area:
(Briefly describe the major topographic features (wetlands, marshes, mountain ranges, dunes etc.) which most typically characterize the landscape of the area).
### 11.2 Altitudinal range
- 11.2.1 Highest elevation above sea level: _____________ metres
- 11.2.2 Lowest elevation above sea level: ______________ metres
- 11.2.3 For coastal/marine areas, maximum depth below mean sea level: ____________ metres

### 11.3. Climate:
(Briefly describe the climate of the area, you may wish to use the regional climate classification by Köppen as suggested by WMO (http://www.wmo.int/pages/themes/climate/understanding_climate.php)).
- 11.3.1 Average temperature of the warmest month: __________ °C
- 11.3.2 Average temperature of the coldest month: __________ °C
- 11.3.3 Mean annual precipitation: ___________ mm, recorded at an elevation of ___________ metres
- 11.3.4 Is there a meteorological station in or near the proposed biosphere reserve? If so, what is its name and location and how long has it been operating?

### 11.4. Geology, geomorphology, soils:
(Briefly describe important formations and conditions, including bedrock geology, sedimentary deposits, and important soil types).

### 11.5 Bioclimatic zone:
(Indicate the bioclimatic region in which the proposed biosphere reserve is located, refer to the table below and tick the appropriate box for each area of the biosphere reserve).

Areas|Average annual rainfall/mm|Penman Aridity index|(UNEP index) Aridity index|Core area(s)|Buffer  zone(s)|Transition area(s)
-|-|-|-|-|-|-
Hyper-arid|P<100| <0.05| <0.05|||
Arid|100-400|0.05-0.28|0.05-0.20|||
Semi-arid|400-600|0.28-0.43|0.21-0.50|||
Dry Sub-humid|600-800|0.43-0.60|0.51-0.65|||
Moist Sub-humid|800-1200|0.60-0.90|>0.65|||
Per-humid|P>1200|>0.90||||
  
Table 1: Aridity index resulting from the use of P/ETP
Mean annual precipitation (P)/mean annual potential evapotranspiration (ETP)

### 11.6 Biological characteristics:
List main habitat types (e.g. tropical evergreen forest, savanna woodland, alpine tundra, coral reef, kelp beds) and land cover types (e.g. residential areas, agricultural land, pastoral land, cultivated areas, rangeland).
 For each type, indicate:
#### REGIONAL:
- if the habitat or land cover type is widely distributed within the biogeographical region within which the proposed biosphere reserve is located, to assess the habitat's or land cover type's representativeness;
#### LOCAL:
- if the habitat or land cover type is of limited distribution within the proposed biosphere reserve, to assess the habitat's or land cover type's uniqueness.
For each habitat or land cover type, list characteristic species and describe important natural processes (e.g. tides, sedimentation, glacial retreat, natural fire) or human impacts (e.g. grazing, selective cutting, agricultural practices) affecting the system. As appropriate, refer to the vegetation or land cover map provided as supporting documentation.

**Comment by zacharlie** [comment]
### 11.5 Bioclimatic zone

Obtaining regional climate data proved challenging, however a map service was found to be available frm the Western Cape Department of Agriculture which had national coverage and is available from the URL: https://gis.elsenburg.com/arcgis/rest/services/Climate/MapServer/13

The source for this data is listed as: SA Atlas of Climatology and Agrohydrology (R.E. Schulze, 2009)

The map service was available as a rendered image, so in order to categorise the image for analysis it was exported (at a resolution of 1000m - EPSG:3857) and the relevant values were extracted from the RGB data based on the Band 1 (Red) value. Where the same value was identified, a combination of Band 1 and Band 2(blue). The relevant categories were outlined as follows (note that the original classification values appear to be in mm per annum):

category 1 - < 100 [232]
category 2 - 100 - 200: [240]
category 3 - 200 - 300: [247]
category 4 - 300 - 400: [250]
category 5 - 400 - 500: 252, 193
category 6 - 500 - 600: 252,234
category 7 - 600 - 700: 233
category 8 - 700 - 800: 202
category 9 - 800 - 900: 168
category 10 - 900 - 1000: 134
category 11 - 1000 - 2000: 94
category 12 - > 2000: 40

These were used to produce a new raster with the QGIS raster calculator and the following calculation:

```
("raster@1"=232)*1 +
("raster@1"=240)*2 +
("raster@1"=247)*3 +
("raster@1"=250)*4 +
("raster@1"=252 AND "raster@2"=193)*5 +
("raster@1"=252 AND "raster@2"=234)*6 +
("raster@1"=233)*7 +
("raster@1"=202)*8 +
("raster@1"=168)*9 +
("raster@1"=134)*10 +
("raster@1"=94)*11 +
("raster@1"=40)*12
```

This image was used to calculate zonal statistics for each of the proposed biosphere areas with the results outlined in the following table.

| zone       | pr_mean          | pr_median | pr_min | pr_max | pr_range | pr_variance       |
|------------|------------------|-----------|--------|--------|----------|-------------------|
| core       | 5.82726130653266 | 6         | 4      | 8      | 4        | 0.494658831216408 |
| transition | 5.59002106876077 | 6         | 4      | 8      | 4        | 0.641436525125875 |
| buffer     | 5.85049078864658 | 6         | 4      | 8      | 4        | 0.53216563601826  |

From this analysis (and the accompanying map), it was determined that all areas predominantly receive a mean annual rainfall of between 400 - 600mm and may be classified as Semi-arid regions.

Areas|Average annual rainfall/mm|Penman Aridity index|(UNEP index) Aridity index|Core area(s)|Buffer  zone(s)|Transition area(s)
-|-|-|-|:-:|:-:|:-:
Hyper-arid|P<100| <0.05| <0.05|||
Arid|100-400|0.05-0.28|0.05-0.20|||
Semi-arid|400-600|0.28-0.43|0.21-0.50|x|x|x
Dry Sub-humid|600-800|0.43-0.60|0.51-0.65|||
Moist Sub-humid|800-1200|0.60-0.90|>0.65|||
Per-humid|P>1200|>0.90||||

![Mean Annual Rainfall](https://user-images.githubusercontent.com/64078329/101140133-34a24a00-361b-11eb-8dd7-a3cc60fdc653.png)

**Comment by zacharlie** [comment]
The following screenshot shows the national mean annual rainfall data for reference purposes and utilises the same legend item as the map referenced above

![image](https://user-images.githubusercontent.com/64078329/101140747-0cffb180-361c-11eb-8103-42a4e46009fa.png)

**Comment by zacharlie** [comment]
### 11.6 Biological characteristics (Draft)

A preliminary outline of the coverage for regional habitat types from the 2018 NBA data has been outlined in #54 

Coverage analysis at national level is ongoing. A table with details on vegetation types within the Waterberg District is outlined in the Waterberg  District Bioregional Plan in _Table 2. Summary of vegetation types, with national ecosystem threat status, levels of endemism and ecosystem protection for the Waterberg District, based on the NBA 2011 and the Limpopo Conservation Plan (LCPv2) (Desmet et al., 2013)._

**Landuse**

Overlap analysis of data obtained from the NGI and produced b the DEA for landcover and landuse areas (aggregated by feature type) is outlined in the table below.

|                           | Core       | Buffer    | Transition |
|---------------------------|------------|-----------|------------|
| Barren Lands (ha)         | 0.0000     | 10.1226   | 25.5735    |
| Cultivated Land (ha)      | 25080.6811 | 0.0000    | 0.0000     |
| Forest and Woodlands (ha) | 1582.5816  | 0.0000    | 923.6751   |
| Orchard or Vineyard (ha)  | 208.9182   | 1859.9155 | 1188.3670  |
| Plantation (ha)           | 0.0000     | 26.8602   | 0.0000     |
| Residential (ha)          | 192.3334   | 6279.1486 | 21852.0615 |


|                           | Core       | Buffer    | Transition |
|---------------------------|------------|-----------|------------|
| Barren Lands %            | 0.0000     | 0.0006    | 0.0032     |
| Cultivated Land %         | 3.4050     | 0.0000    | 0.0000     |
| Forest and Woodlands %    | 0.2149     | 0.0000    | 0.1152     |
| Orchard or Vineyard %     | 0.0284     | 0.1168    | 0.1483     |
| Plantation %              | 0.0000     | 0.0017    | 0.0000     |
| Residential %             | 0.0261     | 0.3944    | 2.7262     |

**Comment by gubuntu** [comment]
impressive @zacharlie  and @seabilwe !

**Comment by gubuntu** [comment]
# update Nov 2022

 landcover (2020) per zone 

"class_name"	"core_ha"	"buffer_ha"	"transition_ha"
"contiguous low forest & thicket"	944	2457	523
"dense forest & woodland"	123132	198001	72931
"open woodland"	594580	901415	297709
"contiguous & dense plantation forest"	258	931	233
"open & sparse plantation forest"	319	1316	405
"temporary unplanted (clear-felled) plantation forest"	0	50	93
"sparsely wooded grassland"	2184	816	176
"natural grassland"	157515	181414	50411
"natural rivers"	336	1104	97
"natural pans (flooded @ observation times)"	22	75	12
"artificial dams (including canals)"	1692	1935	501
"artificial sewage ponds"	0	10	13
"artificial flooded mine pits"	71	226	136
"herbaceous wetlands (currently mapped)"	2151	2179	703
"herbaceous wetlands (previously mapped)"	3999	6332	1034
"natural rock surfaces"	7787	3072	617
"dry pans"	32	67	30
"eroded lands"	1098	2997	1921
"bare riverbed material"	263	435	187
"other bare"	1985	1420	569
"cultivated commercial permanent orchards"	189	2219	574
"commercial annual crops pivot irrigated"	4950	42159	4047
"commercial annual crops non-pivot irrigated"	39	1105	15
"commercial annual crops rain-fed / dryland"	27040	98254	40531
"subsistence / small-scale annual crops"	278	17082	61145
"fallow land & old fields (trees)"	3380	12193	5589
"fallow land & old fields (bush)"	29695	88144	47463
"fallow land & old fields (grass)"	3434	7783	3923
"fallow land & old fields (bare)"	43	118	49
"residential formal (tree)"	198	915	1537
"residential formal (bush)"	602	5538	17002
"residential formal (low veg / grass)"	181	4741	11637
"residential formal (bare)"	136	1634	2337
"residential informal (tree)"	2	9	41
"residential informal (bush)"	40	87	272
"residential informal (low veg / grass)"	8	170	225
"residential informal (bare)"	5	119	139
"village scattered (bare & low veg/ grss combo)"	206	865	1046
"village dense (bare & low veg / grss combo)"	20	326	471
"smallholdings (tree)"	696	381	334
"smallholdings (bush)"	1070	4101	3006
"smallholdings (low veg / grass)"	286	860	215
"smallholdings (bare)"	10	39	17
"urban recreational fields (tree)"	3	151	116
"urban recreational fields (bush)"	42	341	348
"urban recreational fields (grass)"	22	229	186
"urban recreational fields (bare)"	0	9	2
"commercial"	14	229	411
"industrial"	141	696	399
"roads & rails (major linear)"	774	2196	856
"mines: surface infrastructure"	121	151	290
"mines: extraction pits, quarries"	441	763	714
"mine: tailings and resource dumps"	974	1802	2465
"land-fills"	0	2	6
"fallow land & old fields (wetlands)"	104	452	134

**Comment by gubuntu** [comment]
## Vegetation type (Mucina and Rutherford 2018) by zone

"zone"	"veg"	"area_ha"
"buffer"	"Waterberg Mountain Bushveld"	400484
"buffer"	"Central Sandy Bushveld"	349859
"buffer"	"Roodeberg Bushveld"	195485
"buffer"	"Western Sandy Bushveld"	169384
"buffer"	"Limpopo Sweet Bushveld"	168683
"buffer"	"Dwaalboom Thornveld"	129213
"buffer"	"Springbokvlakte Thornveld"	65078
"buffer"	"Makhado Sweet Bushveld"	48727
"buffer"	"Polokwane Plateau Bushveld"	30413
"buffer"	"Waterberg-Magaliesberg Summit Sourveld"	12360
"buffer"	"Subtropical Alluvial Vegetation"	9890
"buffer"	"Madikwe Dolomite Bushveld"	9771
"buffer"	"Mamabolo Mountain Bushveld"	5414
"buffer"	"Strydpoort Summit Sourveld"	2067
"core"	"Waterberg Mountain Bushveld"	343850
"core"	"Western Sandy Bushveld"	147721
"core"	"Dwaalboom Thornveld"	108633
"core"	"Roodeberg Bushveld"	96927
"core"	"Central Sandy Bushveld"	94115
"core"	"Limpopo Sweet Bushveld"	46440
"core"	"Springbokvlakte Thornveld"	35243
"core"	"Waterberg-Magaliesberg Summit Sourveld"	33309
"core"	"Polokwane Plateau Bushveld"	14241
"core"	"Mamabolo Mountain Bushveld"	13354
"core"	"Makhado Sweet Bushveld"	12241
"core"	"Madikwe Dolomite Bushveld"	8433
"core"	"Strydpoort Summit Sourveld"	8193
"core"	"Poung Dolomite Mountain Bushveld"	6435
"core"	"Subtropical Alluvial Vegetation"	4330
"transition"	"Makhado Sweet Bushveld"	248122
"transition"	"Waterberg Mountain Bushveld"	122161
"transition"	"Central Sandy Bushveld"	111205
"transition"	"Roodeberg Bushveld"	55717
"transition"	"Polokwane Plateau Bushveld"	49534
"transition"	"Dwaalboom Thornveld"	16731
"transition"	"Springbokvlakte Thornveld"	13933
"transition"	"Western Sandy Bushveld"	7163
"transition"	"Waterberg-Magaliesberg Summit Sourveld"	4410
"transition"	"Limpopo Sweet Bushveld"	3871
"transition"	"Mamabolo Mountain Bushveld"	3145
"transition"	"Madikwe Dolomite Bushveld"	50
"transition"	"Subtropical Alluvial Vegetation"	9

**Comment by gubuntu** [comment]
bioregions / biomes (savannah, grassland and azonal)

<img width="801" alt="Screenshot 2022-10-30 at 15 05 14" src="https://user-images.githubusercontent.com/496911/200158597-7790773c-adad-4e42-9ebe-d154d9d91088.png">
