### ISSUE TITLE
15. describe development function

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#55]
15. DEVELOPMENT FUNCTION:

15.1. Potential for fostering economic and human development which is socio-culturally and ecologically sustainable:

- [x] 15.1.1 Describe how and why the area has potential to serve as a site of excellence/model region for promoting sustainable development.
- [x] 15.1.2 How do you assess changes and successes (which objectives and by which indicator)?

15.2. If tourism is a major activity:

- [x] 15.2.1 Describe the type(s) of tourism and the touristic facilities available. Summarize the main touristic attractions in the proposed biosphere reserve and their location(s).
- [x] 15.2.2 How many visitors come to the proposed biosphere reserve each year? (Distinguish between single-day visitors and overnight guests, visitors only visiting the proposed biosphere reserve or only passing on the way to another place). Is there an upward or downward trend, or a particular target?
- [x] 15.2.3 How are tourism activities currently managed?
- [x] 15.2.4 Indicate possible positive and/or negative impacts of tourism at present or foreseen and how they will be assessed (linked to section 14)?
- [x] 15.2.5 How will these impacts be managed, and by whom?

15.3. Agricultural (including grazing) and other activities (including traditional and customary):

- [x] 15.3.1 Describe the type of agricultural (including grazing) and other activities, area concerned and people involved (including men and women).
- [x] 15.3.2 Indicate the possible positive and/or negative impacts of these activities on biosphere reserve objectives (section 14).
- [x] 15.3.3 Which indicators are, or will be used to assess the state and its trends?
- [ ] 15.3.4 What actions are currently undertaken, and which measures will be applied to strengthen positive impacts or reduce negative impacts on the biosphere reserve objectives?

15.4 Other types of activities positively or negatively contributing to local sustainable development, including impact/influence of the biosphere reserve outside its boundaries.

- [x] 15.4.1 Describe the type of activities, area concerned and people involved (including men and women).
- [x] 15.4.2 Indicate the possible positive and/or negative impacts of these activities on biosphere reserve objectives (section 14). Have some results already been achieved?
- [x] 15.4.3 What indicators are, or will be used to assess the state and its trends?
- [ ] 15.4.4 What actions are currently undertaken, and which measures will be applied to strengthen positive impacts or reducing negative ones on the biosphere reserve objectives?

15.5 Benefits of economic activities to local people:

- [x] 15.5.1 For the activities described above, what income or benefits do local communities (including men and women) derive directly from the site proposed as a biosphere reserve and how?
- [x] 15.5.2 What indicators are used to measure such income or other benefits?

15.6 Spiritual and cultural values and customary practices: (Provide an overview of values and practices, including cultural 
diversity).

- [x] 15.6.1 Describe any cultural and spiritual values and customary practices including languages, rituals, and traditional livelihoods. Are any of these endangered or declining?
- [x] 15.6.2 Indicate activities aimed at identifying, safeguarding, promoting and/or revitalising such values and practices.
- [x] 15.6.3 How should cultural values be integrated in the development process: elements of identity, traditional knowledge, social organizations, etc.?
- [x] 15.6.4 Specify whether any indicators are used to evaluate these activities. If yes, which ones and give details.
(Examples of indicators: presence and number of formal and non-formal education programmes that transmit these values and practices, number of revitalisation programmes in place, number of speakers of an endangered or minority language).

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by seabilwe** [comment]
Using these links for information

http://www.waterberg.gov.za/index.php?page=agriculture
http://www.waterberg.gov.za/index.php?page=tourism

**Comment by seabilwe** [comment]
## 15. DEVELOPMENT FUNCTION:

### 15.1. Potential for fostering economic and human development which is socio-culturally and ecologically sustainable:

- [ ] 15.1.1 Describe how and why the area has potential to serve as a site of excellence/model region for promoting sustainable development.
- [ ] 15.1.2 How do you assess changes and successes (which objectives and by which indicator)?

###15.2. If tourism is a major activity:

- [ ] 15.2.1 Describe the type(s) of tourism and the touristic facilities available. Summarize the main touristic attractions in the proposed biosphere reserve and their location(s).
- [ ] 15.2.2 How many visitors come to the proposed biosphere reserve each year? (Distinguish between single-day visitors and overnight guests, visitors only visiting the proposed biosphere reserve or only passing on the way to another place). Is there an upward or downward trend, or a particular target?
- [ ] 15.2.3 How are tourism activities currently managed?
- [ ] 15.2.4 Indicate possible positive and/or negative impacts of tourism at present or foreseen and how they will be assessed (linked to section 14)?
- [ ] 15.2.5 How will these impacts be managed, and by whom?

### 15.3. Agricultural (including grazing) and other activities (including traditional and customary):

- [ ] 15.3.1 Describe the type of agricultural (including grazing) and other activities, area concerned and people involved (including men and women).
- [ ] 15.3.2 Indicate the possible positive and/or negative impacts of these activities on biosphere reserve objectives (section 14).
- [ ] 15.3.3 Which indicators are, or will be used to assess the state and its trends?
- [ ] 15.3.4 What actions are currently undertaken, and which measures will be applied to strengthen positive impacts or reduce negative impacts on the biosphere reserve objectives?

### 15.4 Other types of activities positively or negatively contributing to local sustainable development, including impact/influence of the biosphere reserve outside its boundaries.

- [ ] 15.4.1 Describe the type of activities, area concerned and people involved (including men and women).
- [ ] 15.4.2 Indicate the possible positive and/or negative impacts of these activities on biosphere reserve objectives (section 14). Have some results already been achieved?
- [ ] 15.4.3 What indicators are, or will be used to assess the state and its trends?
- [ ] 15.4.4 What actions are currently undertaken, and which measures will be applied to strengthen positive impacts or reducing negative ones on the biosphere reserve objectives?

### 15.5 Benefits of economic activities to local people:

- [ ] 15.5.1 For the activities described above, what income or benefits do local communities (including men and women) derive directly from the site proposed as a biosphere reserve and how?
- [ ] 15.5.2 What indicators are used to measure such income or other benefits?

### 15.6 Spiritual and cultural values and customary practices: (Provide an overview of values and practices, including cultural 
diversity).

- [ ] 15.6.1 Describe any cultural and spiritual values and customary practices including languages, rituals, and traditional livelihoods. Are any of these endangered or declining?
- [ ] 15.6.2 Indicate activities aimed at identifying, safeguarding, promoting and/or revitalising such values and practices.
- [ ] 15.6.3 How should cultural values be integrated in the development process: elements of identity, traditional knowledge, social organizations, etc.?
- [ ] 15.6.4 Specify whether any indicators are used to evaluate these activities. If yes, which ones and give details.
(Examples of indicators: presence and number of formal and non-formal education programmes that transmit these values and practices, number of revitalisation programmes in place, number of speakers of an endangered or minority language).

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by zacharlie** [comment]
### 15.1.1 Describe how and why the area has potential to serve as a site of excellence/model region for promoting sustainable development.

The region has large portions of natural or near natural land cover. Very little of the district region is urbanised, and the majority of economic acivity is restricted to the agriculture, wildlife and mining industries. Many local communities are dependant on the availability and protection of local ecological infrastructure, providing strong support from local communities to be involved with governance and conservation plans. Growth in the tourism industry provides significant economic incentive for numerous stakeholders, in private and public sectors, to ensure that sustainable development plans receive the required support to ensure their success.

The Waterberg district contains a large number of private conservation areas (when compared with surrounding regions and other areas within the Republic of South Africa), and also contains numerous national parks with additional legal protection. Existing UNESCO MAB Biosphere reserve areas may be found within the district, as well as in neighbouring regions, as well as coverage of national Important Bird Areas (IBAs) and the Nyl river RAMSAR site. Many of these areas are important for the preservation of biodiversity, climate change resilience and the protection of numerous endemic and sensitive species.

The existing cooperative governance model provides support at numerous levels from multiple public agencies, including the Waterberg District regional planning divisions, Limpopo Provincial government via the Limpopo Department of Economic Development, Environment and Tourism (LEDET), The regional and national Department of Rural Development and Land reform, as well as National legislation regarding governance including the SPLUMA act. In addition, the district already engages with multiple public and private entities on national and international levels.

The Waterberg District Bioregional Plan provides an implementation outline for effective cooperative governance strategy (Guidelines for Land-Use Planning and Decision-Making), as well as the provision of Spatial Development Frameworks and Integrated Deveopment Plans, to ensure sustainable development goals are met, with planned revision to take place within a 5 year minimum revision cycle.

Further information is provided from the following extracts available from the Waterberg District Bioregional Plan (January 2016).

Extract from Waterberg District Bioregional Plan Executive summary

> Agriculture, wildlife and mining are important economic sectors in the region, with plans underway to expand the mining industry as part of the Strategic Integrated Project, particularly along the Northern Mineral Belt. Expansion of the mining industry is one of the Strategic Integrated Projects that is being coordinated by the Presidential Infrastructure Co-ordinating Committee, which forms part of the implementation of the National Development Plan. Wildlife breeding has shown massive expansion in the past 5 years. This is strictly an agricultural activity that is having negative impacts on the natural environment. The Growth in the tourism sector is leading to an increase in game farming, tourism facilities, lifestyle estates and golf estates. Consequently, increasing development pressures on biodiversity and the remaining natural ecosystems should be appropriately managed. These factors together make a bioregional plan a useful tool for addressing the need to take biodiversity into account in land-use planning and decision-making, in order to promote sustainable development.
>
> The Waterberg District falls largely within the Savanna biome, with Grassland biome elements located on the higher peaks of the Waterberg. Three endemic and three near-endemic ecosystem types cover 70% of the Waterberg District. Two nationally listed threatened ecosystems are found in the district. Sixty-four plant species of special concern occur in the District. Twenty-two of these species are threatened. It is also home to three Important Bird Areas of South Africa, reflecting a high diversity of bird species and 21 threatened bird species. There are at least 45 mammal species of special concern in the District, of which 15 are threatened.
>
> Three reptile species of special concern occur, two of which are threatened. Aquatic systems are equally unique, with 72% of the wetland types and 64% of the river types assessed as threatened, providing habitat for at least three Near Threatened freshwater fish species. The region supports numerous endemic species as well, and its unique topography and varied geology sets it apart from the rest of South Africa.
>
> Land-use patterns indicate that approximately 84.8% of the Waterberg District is natural or near-natural land cover. In terms of non natural land cover categories: 1.3% is urban (62.5% change 2009-2014), 10,9% is under dryland cropping (-5% change 2009-2014); 1.6% is under irrigation cropping (24% change 2009-2014); and, 0.31% is under mining (21% change 2009-2014), making up 13.8% as severely or irreversibly modified. Critical Biodiversity Areas (CBAs) cover 51.0% of the Waterberg District; Ecological Support Areas (ESAs) cover a further 14.8% of the District.
>
> Protected Areas cover 4.2% and Conservation Areas 7.6%. Protected Areas and Conservation Areas together cover 11.4% of the Waterberg District. Protected Areas (excluding Conservation Areas), Critical Biodiversity Area and Ecological Support Areas together cover 70.0% of the Waterberg District.

Extract from Waterberg District Bioregional Plan "1 Part A: Introduction and Objectives"

> Mining, agriculture and wildlife are important economic activities within the Waterberg District. Plans are underway to expand the mining industry, particularly within the Northern Mineral Belt (approximately the area north and west of Lephalale [coal], and the Nyl Valley north of Mokopane [platinum group metals]. Expansion of the mining industry is one of the Strategic Integrated Projects that is being coordinated by the Presidential Infrastructure Co-ordinating Committee, which forms part of the implementation of the National Development Plan. Commercial crop farming is largely concentrated in the Modimolle and the Mookgophong local municipal areas, in the “Springbok Flats”, the broad valley towards Alma; and along the major tributaries of the Limpopo (e.g. Crocodile and Mokolo Rivers). Cattle and game farming are also important agricultural activities, with game farming dominant in the Waterberg and Limpopo Valley areas. Agriculture is planned to expand, especially in the Lephalale, Modimolle and Mookgophong local municipalities. The game farming industry is rapidly expanding driven mainly by grow in the colour-morph breeding market. Conversion of extensive grazing farms to high intensity breeding farms is having significant negative environmental impacts (overgrazing and loss of landscape connectivity). The growing tourism sector (ecotourism and hunting) is also a major contributor to economic growth that is leading to an increase in traditional game farming, private lodges and tourism facilities. Lifestyle and golf estates are also an important growth industry in the district supporting local construction and service industries. Industrial development is secondary, with small scale manufacturing and services concentrated around Bela-Bela, Thabazimbi and Mokopane (EMF, 2010a; EMF, 2010b). This is set to change as mining and power generation in the Northern Mineral Belt expand in the coming decade.
>
> These activities are all associated with land-use change and associated loss or degradation of natural habitat, biodiversity and ecosystems. The pressures placed on the environment and the remaining natural ecosystems are accelerating with new economic developments unfolding in the Waterberg District. Further loss of natural habitat and ecological infrastructure is expected. Consequently, a bioregional plan for the Waterberg District is an appropriate tool for addressing the need to take biodiversity into account in land-use planning and decision-making, in order to promote sustainable development.

**Comment by zacharlie** [comment]
### 15.1.2 How do you assess changes and successes (which objectives and by which indicator)?

The Waterberg District utilises Integrated Development Plans, which are used to ensure environmental sustainability and reflect multi-sectoral planning at the municipal level. The Bioregional plan forms only one component of the Environmental Sector Plan, which covers a range of environmental management issues, such as the control of wastewater discharge and air pollution. Additional IDPs cover projects for human factors, such as poverty alleviation and gender equity, and economic development, such as Local Economic Development (LEDs) and captial investment programmes.

More details on these programmes and their implementation strategy is detailed in the Waterberg District Bioregional Plan – Table 14. A guide to incorporating the Bioregional Plan into IDPs and SDFs (adapted from the Pierce and Mader (2006)).

Sustainable development objectives are assessed in line with the objectives of the Waterberg District Bioregional Plan. This plan is revised at intervals of a minimum of 5 years to ensure that planning programs stay in line with sustainsable development and biodiversity management goals.

A summary of the planning programmes used for the Waterberg Biosphere Reserve Zones is detailed in the Waterberg District Bioregional Plan – Waterberg District Bioregional Plan – Table 15: Summary of Guidelines for the Waterberg Biosphere Reserve Zones (Contour and Associates, 2011).

The plan outlines the utilisation of Spatial Development Frameworks (often at a municipal level), which are reviewed and updated and implemented in line with the SPLUMA act guidelines. This includes the inclusion of an assessment of Critical Biodiversity Areas, an updated Strategic Environmental Assessment and capture of land use changes using GIS.

Biodiversity indicators used are the measurement of Percentage and area (hectares) of Critical Biodiversity Areas and Ecological Support Areas based on the following criteria:

- Are contained within conservation orientated zones within Spatial Development Frameworks, Land Use Schemes and Environmental Management Frameworks.
- Are under some form of conservation management.
- Where subdivision has been approved or where increased development rights have been granted.
- Where appropriate biodiversity management interventions have been applied.
- Have been severely or irreversibly modified due to various land-use changes.
- Are in a natural or near-natural state.
- Have been rehabilitated to an ecological condition.

**Comment by zacharlie** [comment]
### 15.5.1. For the activities described above, what income or benefits do local communities (including men and women) derive directly from the site proposed as a biosphere reserve and how?

Many local communities are dependant on the regional ecological infrastructure. The impacts of economic activities such as mining can have wide reaching effects on ecological infrastructure, especially on the provision and quality of water. By ensuring the deisgnation of key areas as biosphere reserve zones, the stresses applied to this infrastructure may be reduced, ensuring hat planning divisions properly prioritise land use in line with sustainable development goals. Local communities may still benefit from these activites as long as their impact on ecological resources are reduced, as well as benfitting from other sectors of economic growth such as tourism.

**Comment by gubuntu** [comment]
great work @seabilwe and @zacharlie
