### ISSUE TITLE
19.1 location and zonation map

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#57]
Location and zonation map with coordinates
[Provide the biosphere reserve’s standard geographical coordinates (all projected under WGS 84).
Provide a map on a topographic layer of the precise location and delimitation of the three zones of the biosphere reserve (Map(s) shall be provided in both paper and electronic copies). Shapefiles (also in WGS 84 projection system) used to produce the map must also be attached to the electronic copy of the form. If applicable, also provide a link to access this map on the internet (e.g. Google map, website).]

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by seabilwe** [comment]
**UPDATE**
Below is the map on a topographic layer of the precise location and delimitation of the three zones of the biosphere reserve. 
@gbuntu one question regarding this, do they need geographical coordinates of the zones or the AOI that was generated? 
And also the should the coordinates be one point or coordinates of the extent?
![Location and Zonation](https://user-images.githubusercontent.com/56301949/97267458-dff8fb80-1832-11eb-8b15-f306f08945e9.png)

**Comment by seabilwe** [comment]
@gubuntu I went through the maps you uploaded on Drive and you had a this map showing the zones but with the original WBR boundary

**Comment by gubuntu** [comment]
coordinates of the extent of the proposed WBR

bear in mind that the boundaries and zones will change so you need to be able to regenerate all out puts each time they do. 

That map has the wrong title (oops)

**Comment by seabilwe** [comment]
Alright @gubuntu I will fix the title.

**Comment by gubuntu** [comment]
this map should also not show the AOI

**Comment by NyakudyaA** [comment]
For the coordinates i suppose we need to supply the file with these rather than adding it as a table.

**Comment by zacharlie** [comment]
![Location](https://user-images.githubusercontent.com/64078329/101136140-919b0180-3615-11eb-81a4-e4977971c87b.png)

I believe this serves the functional requirement for this and #47 (Section 6.2)

I created an outline by converting the areas to line features and selecting only the features from the outer extent (and parcels that lie outside of this boundary).

For relevant map positions it is expected that geographic coordinates (EPSG:4326) are most useful. While supplying the entire zonation dataset is expected to be done electronically, we can also deliver features in plain text using the geojson format.

For locality purposes, I created a convex hull and extracted the vertices to geographic points, as supplied in the following dataset.

```
{
"type": "FeatureCollection",
"name": "BoundaryConvexHull",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 0, "Long": 27.226122, "Lat": -25.138986 }, "geometry": { "type": "Point", "coordinates": [ 27.226122, -25.138986 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 26.41048763, "Lat": -24.80902205 }, "geometry": { "type": "Point", "coordinates": [ 26.410487627909404, -24.809022049424311 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 26.368039, "Lat": -24.78815 }, "geometry": { "type": "Point", "coordinates": [ 26.368039, -24.78815 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 26.340858, "Lat": -24.649593 }, "geometry": { "type": "Point", "coordinates": [ 26.340858, -24.649593 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 27.76650693, "Lat": -23.13417293 }, "geometry": { "type": "Point", "coordinates": [ 27.766506933637253, -23.134172929688109 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 27.76741693, "Lat": -23.13335193 }, "geometry": { "type": "Point", "coordinates": [ 27.767416933637254, -23.133351929688104 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 27.943683, "Lat": -22.9982545 }, "geometry": { "type": "Point", "coordinates": [ 27.943683, -22.9982545 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 27.950504, "Lat": -22.9974814 }, "geometry": { "type": "Point", "coordinates": [ 27.950504, -22.9974814 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 28.669978, "Lat": -23.1235565 }, "geometry": { "type": "Point", "coordinates": [ 28.669978, -23.1235565 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 29.12083, "Lat": -23.3894694 }, "geometry": { "type": "Point", "coordinates": [ 29.12083, -23.3894694 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 29.1759, "Lat": -23.4489247 }, "geometry": { "type": "Point", "coordinates": [ 29.1759, -23.4489247 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 29.212849, "Lat": -23.4941761 }, "geometry": { "type": "Point", "coordinates": [ 29.212849, -23.4941761 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 29.244649, "Lat": -23.546434 }, "geometry": { "type": "Point", "coordinates": [ 29.244649, -23.546434 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 29.292768, "Lat": -24.1288396 }, "geometry": { "type": "Point", "coordinates": [ 29.292768, -24.1288396 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 29.292714, "Lat": -24.1517381 }, "geometry": { "type": "Point", "coordinates": [ 29.292714, -24.1517381 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 29.21889191, "Lat": -24.2962679 }, "geometry": { "type": "Point", "coordinates": [ 29.218891907423789, -24.29626789595639 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 29.085771, "Lat": -24.4498242 }, "geometry": { "type": "Point", "coordinates": [ 29.085771, -24.4498242 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 28.833522, "Lat": -24.7184147 }, "geometry": { "type": "Point", "coordinates": [ 28.833522, -24.7184147 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 28.801495, "Lat": -24.744908 }, "geometry": { "type": "Point", "coordinates": [ 28.801494999984687, -24.744908000043587 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 28.678165, "Lat": -24.8164861 }, "geometry": { "type": "Point", "coordinates": [ 28.678165, -24.8164861 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 28.493446, "Lat": -24.9149182 }, "geometry": { "type": "Point", "coordinates": [ 28.493446, -24.9149182 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 28.308822, "Lat": -24.9790277 }, "geometry": { "type": "Point", "coordinates": [ 28.308822, -24.9790277 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 28.277341, "Lat": -24.9853482 }, "geometry": { "type": "Point", "coordinates": [ 28.277341, -24.9853482 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 27.58823378, "Lat": -25.10850116 }, "geometry": { "type": "Point", "coordinates": [ 27.588233783465562, -25.108501162580058 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 27.350563, "Lat": -25.1346939 }, "geometry": { "type": "Point", "coordinates": [ 27.350563, -25.1346939 ] } },
{ "type": "Feature", "properties": { "id": 0, "Long": 27.226122, "Lat": -25.138986 }, "geometry": { "type": "Point", "coordinates": [ 27.226122, -25.138986 ] } }
]
}
```

For cartographic purposes, this was modified to include a more even distribution of points to provide locality information. These points were assigned an alphabetical identifier and included as a table on the map.

| Label | Long        | Lat          |
|-------|-------------|--------------|
| A     | 27.95050400 | -22.99748140 |
| B     | 28.66997800 | -23.12355650 |
| C     | 29.12083000 | -23.38946940 |
| D     | 29.24464900 | -23.54643400 |
| E     | 29.29271400 | -24.15173810 |
| F     | 29.21889191 | -24.29626790 |
| G     | 28.83352200 | -24.71841470 |
| H     | 28.27734100 | -24.98534820 |
| I     | 27.22612200 | -25.13898600 |
| J     | 26.36803900 | -24.78815000 |
| K     | 26.34085800 | -24.64959300 |
| L     | 26.86753600 | -24.12353150 |
| M     | 27.50841700 | -23.92663640 |
| N     | 27.65279400 | -23.34915940 |
| O     | 27.76741693 | -23.13335193 |

Note that simply connecting these locality positions may result in some boundary positions being excluded from or overlapping the outlined area and these map positions serve a different purpose to the "Convex Hull" previously described. The modified map position area is represented in the following screenshot which should help identify potential outliers.

![modified_extent_positions](https://user-images.githubusercontent.com/64078329/101138742-4551c080-3619-11eb-9a91-574d82b8dce3.png)

The output map also includes national locality with the OSM map service and regional information by using the OSM topographic map service as a basemap.

The outline data (as line features) may be included here in geojson format, however it currently contains ~500000 characters and is considered verbose. Note that this featureset currently contains dangles which have proved difficult to clean/ remove, and vertices may be extracted from the final dataset as well if a bounding point dataset is required instead.

**Comment by gubuntu** [comment]
thanks @seabilwe and @zacharlie

**Comment by gubuntu** [comment]
updated zones as of 4 Nov 2022

<img width="1069" alt="Screenshot 2022-11-04 at 14 33 21" src="https://user-images.githubusercontent.com/496911/200121403-ad99673f-f984-4bd0-a638-036953ab48ee.png">
