### ISSUE TITLE
generate climate change resilience layer

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#61]
produce each of these layers (add more if missing):
- [x] climate change resilience
  - [x] riparian corridors and buffers
  - [x] biophysical diversity
    - [x] altitude heterogeneity
    - [x] precipitation  heterogeneity
    - [x] temperature  heterogeneity
  - [x] high biotic diversity
    - [x] biome heterogeneity
    - [x] vegetation group heterogeneity
    - [x] vegetation type heterogeneity
  - [x] centres of floral endemism
  - [x] local refugia
    - [x] south facing slopes and kloofs
    - [x] kloofs
  - [x] priority large unfragmented areas

references in the project's '5-operations' Drive folder: 
- Holness_2017_Integrated Spatial Prioritization for KNP Buffer - report for review
- process flow diagram https://app.diagrams.net/#G1cZREmkh4cu7OrkGwQicZs9Ul74JdxWbn aka 'WBR SEMP process flow.drawio'

**Comment by seabilwe** [comment]
- Using the lc_status raster layer to create a cost surface raster. 
- already have filtered the river layer to only show large rivers and 2nd order, for large used perennial 
- created a 500m and 5km buffer, using the rivers layer, but will create a one side buffer

**Comment by gubuntu** [comment]
please get hold of floral endemism data asap so we can use it in the next round

**Comment by gubuntu** [comment]
your composite map seems to be dominated by the biophysical diversity layer. Please review your methodology to ensure it follows Holness and that layers are weighted and combined properly.

**Comment by seabilwe** [comment]
Endemic layer:

Used the layer from the sanbi schema:
![image](https://user-images.githubusercontent.com/56301949/97840453-afaad480-1cec-11eb-87d0-a3dbcc8eb477.png)

Vegetation classed as endemic:
![image](https://user-images.githubusercontent.com/56301949/97840548-e123a000-1cec-11eb-90b0-eac759f88866.png)

Endemic rasterized and clipped to remaining natural habitat, excluding transformed and degraded:
![image](https://user-images.githubusercontent.com/56301949/97840870-76bf2f80-1ced-11eb-9e01-331a17cbf187.png)
