### ISSUE TITLE
generate cumulative ecosystem infrastructure value

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#62]
produce each of these layers (add more if missing):
- [x] cumulative EI value
  - [x] composite ecological infrastructure
    - [x] water production and stream flow augmentation
    - [x] water quality
    - [x] flood attenuation
    - [x] erosion control

references in the project's '5-operations' Drive folder: 
- Holness_2017_Integrated Spatial Prioritization for KNP Buffer - report for review
- process flow diagram https://app.diagrams.net/#G1cZREmkh4cu7OrkGwQicZs9Ul74JdxWbn aka 'WBR SEMP process flow.drawio'

**Comment by zacharlie** [comment]
I have used processing models structured in accordance with the QGIS resource sharing plugin. Would there be a requirement to set this up as a separate git repository or should we just upload the models into the primary directory.

**Comment by gubuntu** [comment]
I think a dedicated directory for those within this repo would suffice for now

**Comment by zacharlie** [comment]
### Composite Ecological Infrastructure

![Composite Ecological Infrastructure](https://user-images.githubusercontent.com/64078329/94609089-a5855880-029e-11eb-8477-c84032fe65cf.png)

### Cumulative Ecological Infrastructure

![Cumulative Ecological Infrastructure](https://user-images.githubusercontent.com/64078329/94609097-a7e7b280-029e-11eb-9010-2569b0c890ee.png)

### Erosion Control

![Erosion Control](https://user-images.githubusercontent.com/64078329/94609113-a9b17600-029e-11eb-879c-0790fa6ed7df.png)

### Flood Attenuation

![Flood Attenuation](https://user-images.githubusercontent.com/64078329/94609291-d2d20680-029e-11eb-9178-263484ef3f2f.png)

### Water Production/ Availability/ stream flow augmentation)

![Water Production](https://user-images.githubusercontent.com/64078329/94609282-d1084300-029e-11eb-89f4-0a925925eb48.png)

### Water Quality

![Water Quality](https://user-images.githubusercontent.com/64078329/94609293-d5346080-029e-11eb-9fda-a886c38a560d.png)

### Strategic Water Areas

![Strategic water areas](https://user-images.githubusercontent.com/64078329/94609295-d6658d80-029e-11eb-817c-58aaa5fb0c20.png)

**Comment by gubuntu** [comment]
nice work @zacharlie, thank you! There are some typos and inconsistencies and SWSA wan't one of your required maps. 

I've put them in our report so the rest of our team can see them and start writing about them. I hope to get around to the overall combination later today. 

Be prepared to make some tweks if and when you get more specific feedback.

**Comment by zacharlie** [comment]
SWSA's were in the original reports so I put it here but left it out of the maps drive folder. I also renamed the protected areas layer appropriately.

**Comment by gubuntu** [comment]
thanks for the updates, I've updated the report with them

**Comment by zacharlie** [comment]
Reopening as these models will probably have to be readjusted using a more raster-centric processing approach to facilitate scalability, automation and future updates

**Comment by zacharlie** [comment]
This process was updated with a raster-centric processing approach, new SWSA data, a revised implementation of the cumulative ei calculation and revised cartography to better represent the resulting data.

### Cumulative Ecological Infrastructure

![Cumulative Ecological Infrastructure](https://user-images.githubusercontent.com/64078329/96488129-d32a4580-123d-11eb-8f7e-edcc62c0104e.png)

### Composite Ecological Infrastructure

![Composite Ecological Infrastructure](https://user-images.githubusercontent.com/64078329/96488124-d0c7eb80-123d-11eb-804b-b2c46e42e087.png)

### Erosion Control

![Erosion Control](https://user-images.githubusercontent.com/64078329/96488131-d3c2dc00-123d-11eb-8f22-d9af4d550a5f.png)

### Flood Attenuation

![Flood Attenuation](https://user-images.githubusercontent.com/64078329/96488135-d45b7280-123d-11eb-8427-02f74f15d27d.png)

### Water Production

![Water Production](https://user-images.githubusercontent.com/64078329/96488137-d58c9f80-123d-11eb-9887-eb36b63152e8.png)

### Water Quality

![Water Quality](https://user-images.githubusercontent.com/64078329/96488142-d6253600-123d-11eb-8b2a-39ff7dbfd9d0.png)
