### ISSUE TITLE
generate integrated social demand index

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#63]
produce each of these layers (add more if missing):
- [x] integrated social demand index on intact habitats
  - [x] integrated social demand index
    - [x] poverty index
      - [x] proportion of low-income households
      - [x] dependency ratio index
      - [x] access to services index
      - [x] consumption (lack of goods) index
    - [x] local direct natural resource dependence
      - [x] supply of building materials
      - [x] use of wood for cooking
      - [x] use of wood for heating
      - [x] direct supply of water from the environment

references in the project's '5-operations' Drive folder: 
- Holness_2017_Integrated Spatial Prioritization for KNP Buffer - report for review
- process flow diagram https://app.diagrams.net/#G1cZREmkh4cu7OrkGwQicZs9Ul74JdxWbn aka 'WBR SEMP process flow.drawio'

**Comment by NyakudyaA** [comment]
> produce each of these layers (add more if missing):
> 
>     * [ ]  integrated social demand index on intact habitats
>       
>       * [ ]  integrated social deman index
>         
>         * [ ]  poverty index
>           
>           * [ ]  proportion of low-income households
>           * [ ]  dependency ratio index
>           * [ ]  access to services index
>           * [ ]  consumption (lack of goods) index
>         * [ ]  local direct natural resource dependence
>           
>           * [ ]  supply of building materials
>           * [ ]  use of wood for cooking
>           * [ ]  use of wood for heating
>           * [ ]  direct supply of water from the environment
> 
> 
> references in the project's '5-operations' Drive folder:
> 
>     * Holness_2017_Integrated Spatial Prioritization for KNP Buffer - report for review
> 
>     * process flow diagram https://app.diagrams.net/#G1cZREmkh4cu7OrkGwQicZs9Ul74JdxWbn aka 'WBR SEMP process flow.drawio'

@gubuntu I have made a start at creating the model for this but for the `proportion of low-income households` I have managed to source the data
![low-income](https://user-images.githubusercontent.com/2510900/93892466-d983db00-fcec-11ea-9b46-84688457fc2d.png)
![Low_income_households](https://user-images.githubusercontent.com/2510900/93892571-f4eee600-fcec-11ea-9d83-134b8c7b3a74.png)

**Comment by NyakudyaA** [comment]
* Dependency ratio index
![dependency-ratio](https://user-images.githubusercontent.com/2510900/94459546-cd4dc100-01b7-11eb-89fb-37e01dc1cb37.png)

* Low Income
![low-incomes](https://user-images.githubusercontent.com/2510900/94459704-07b75e00-01b8-11eb-9b5e-435d488dbe72.png)

I am not very comfortable with the way I have done the formulae I used here. 

Data sourced from https://www.datafirst.uct.ac.za/dataportal/index.php/catalog/517/get_microdata

**Comment by gubuntu** [comment]
where's your poverty index map?

**Comment by NyakudyaA** [comment]
> where's your poverty index map?

In put it in drive

**Comment by gubuntu** [comment]
it's not there. I also still don't like the big polygons in the dependency ratio map, think about how to improve that for the next round.

**Comment by gubuntu** [comment]
you also ticked Access to services but that map isn't in Drive (did you use it in your analysis at least?)

**Comment by gubuntu** [comment]
did you try to generate the final map at all? (summarising by quinary catchment)

**Comment by NyakudyaA** [comment]
> did you try to generate the final map at all? (summarising by quinary catchment)

I will put show the output here first and you can comment first.

**Comment by NyakudyaA** [comment]
> you also ticked Access to services but that map isn't in Drive (did you use it in your analysis at least?)

I should untick it. I could didn't use it in the analysis because i did not trust the data as it was not what we needed.

**Comment by NyakudyaA** [comment]
> it's not there. I also still don't like the big polygons in the dependency ratio map, think about how to improve that for the next round.

Yes, I will look up to see why it came like this. If I find the solution I will update the map

**Comment by gubuntu** [comment]
Please fix ASAP!

@NyakudyaA I missed in the meeting that there are several missing maps in drive and several that still need to be updated.

and although your final tif output in minio was good there is not a map in drive for that

And for maps that you did update they're missing the towns layer and you left the survey_villages item in the legend.

**Comment by NyakudyaA** [comment]
> Please fix ASAP!
> 
> @NyakudyaA I missed in the meeting that there are several missing maps in drive and several that still need to be updated.
> 
> and although your final tif output in minio was good there is not a map in drive for that
> 
> And for maps that you did update they're missing the towns layer and you left the survey_villages item in the legend.

Will do it now and update them

**Comment by gubuntu** [comment]
thanks for updates, but some still need work. I've unticked those that are missing or not right

even building materials and some others don't look right with large areas of pink in non-poor areas yet large areas of white in poor areas?

also fix spelling of biosphere in legends

**Comment by NyakudyaA** [comment]
@gavin the dependency ratio generates high values for all areas using the given 

(100 - (Ratio employed/100))/10 where the ratio employed = `employed / sum ( unemployed + dosicoraged_worker_seeker + not_economically_active + less_than_15 + employed)`

Example of a dataset that I have used
[dependency_ratio.zip](https://github.com/kartoza/WBR-SEMP/files/5506509/dependency_ratio.zip)

**Comment by gubuntu** [comment]
correction: ratio employed = employed / sum ( unemployed + dosicoraged_worker_seeker + not_economically_active + less_than_15)

this is what I get

![Screenshot 2020-11-09 at 17 22 04](https://user-images.githubusercontent.com/496911/98560380-63453300-22b0-11eb-850d-3acdf5b35d51.png)

and what some of the data looks like (with the two fields I calculated)

![Screenshot 2020-11-09 at 17 25 12](https://user-images.githubusercontent.com/496911/98560549-8bcd2d00-22b0-11eb-9a15-96edd16b4115.png)

I'm not sure what Holness means in his statement on population density. The numbers should be converted to densities first, it's just not clear how he did it. But you need to do that and end up with scores from 0-10 (and for your other layers too)

PS: could you share the 'raw' data you got from the datafirst url (I don't want to have to apply separately). Simplest would be to load it into the Kartoza cloud PG DB or wbr DB as appropriate

**Comment by NyakudyaA** [comment]
> correction: ratio employed = employed / sum ( unemployed + dosicoraged_worker_seeker + not_economically_active + less_than_15)
> 
> this is what I get
> 
> ![Screenshot 2020-11-09 at 17 22 04](https://user-images.githubusercontent.com/496911/98560380-63453300-22b0-11eb-850d-3acdf5b35d51.png)
> 
> and what some of the data looks like (with the two fields I calculated)
> 
> ![Screenshot 2020-11-09 at 17 25 12](https://user-images.githubusercontent.com/496911/98560549-8bcd2d00-22b0-11eb-9a15-96edd16b4115.png)
> 
> I'm not sure what Holness means in his statement on population density. The numbers should be converted to densities first, it's just not clear how he did it. But you need to do that and end up with scores from 0-10 (and for your other layers too)
> 
> PS: could you share the 'raw' data you got from the datafirst url (I don't want to have to apply separately). Simplest would be to load it into the Kartoza cloud PG DB or wbr DB as appropriate

I initially tried that formulae and those are the same values I get as well. When you use the values to generate the index it will produce a raster with very high values and in turn this will affect the poverty index and the other indices. 
![values](https://user-images.githubusercontent.com/2510900/98562092-56c1da00-22b2-11eb-9c2d-74b795145402.png)

I have added the table to the public schema as `employment-status-hhold-head` All the other ones are fine except this one that has values skewed on the upper 9 mostly

Where the column values are depict 

emsthhh_1 | Employed - Employment status of household head |  
-- | -- | --
emsthhh_2 | Unemployed - Employment status of household head |  
emsthhh_3 | Discouraged work-seeker - Employment status of household head |  
emsthhh_4 | Other not economically active - Employment status of household head |  
emsthhh_5 | Age less than 15 years - Employment status of household head |

**Comment by gubuntu** [comment]
I've unticked the two you were going to update

**Comment by NyakudyaA** [comment]
I have updated the maps

**Comment by gubuntu** [comment]
thanks!
