### ISSUE TITLE
clear confusion in 49-50

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#8]
49 has an irrigation question in addition to the area question and 50 actually contains 3 questions - split these out into sensible Mergin questions

**Comment by seabilwe** [comment]
I had slit the irrigation question from the area question, and with 50 there's only one question that I had separated

**Comment by seabilwe** [comment]
@gubuntu the questions have been split up, the ones 50 have been made to depend on the main question.
