### ISSUE TITLE
split Regorogile into two samples?

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#82]
I've merged the Regorogile sample into one (about 80) - if we want to split it into two extensions (ext4 and ext8) then I need guidance on the boundary between the two groups

**Comment by LetticiaWBR** [comment]
@gubuntu I am not sure if we should keep it as one sample or not, Thabazimbi is like Modimolle/Phagameng it is made up of township and urban area, Regorogile is the tonship (land mark ill be Waterberg TVET College, the public hopsital, Home affairs and Mbogomapedi High School) that whole section is the township. Then there is the urban part of it this will be sections behind the town (landmark is SPAR, Shoprite). I say lets keep it as one section and we will then describe it as ext 1-6 and the town part.
