### ISSUE TITLE
make two village survey maps

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#83]
- [x] Like the A0 map you made for the workshop, make an A4 version
- [x] Make another A4 map in a copy of the above A4 template, but replacing the village survey polygon layer with "wbr_survey.wbr_wash_village survey", which shows in which villages Lesiba conducted the village-level survey with village heads, and zooming in to its extent.

**Comment by seabilwe** [comment]
@gubuntu here are the maps below. Please advise on the title for the `wbr_wash_village_survey` . I have uploaded them ti the Biosphere folder on GDRIVE
![Suvery villages](https://user-images.githubusercontent.com/56301949/98592812-ebd8c900-22da-11eb-8e9f-709ebc4dcf34.png)
![Wash Village Survey](https://user-images.githubusercontent.com/56301949/98592831-f09d7d00-22da-11eb-8727-54fec752dfa9.png)
