### ISSUE TITLE
Optimise QGIS project published on site

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/WBR-SEMP#86]
I have added the XYZ tiles as base maps and they should be removed from the QGIS project

![base-maps](https://user-images.githubusercontent.com/2510900/104092814-0f929e00-528f-11eb-8600-d9b31b845560.png)

This will make sure that QGIS Server does not render these but are served directly from the source

**Comment by zacharlie** [comment]
Basemaps group removed and projects uploaded
