### ISSUE TITLE
Troubleshoot map performance issues

### ISSUE THREAD

**Issue by zacharlie** [kartoza/WBR-SEMP#91]
@NyakudyaA started a discussion with the development team in https://github.com/g3w-suite/g3w-suite-docker/issues/25

It is my suspicion that the utilisation of the python API is causing performance bottlenecks via the use of a single thread (GIL), which may be causing the primary performance problems.

**Comment by lkwalke4** [comment]
@lucernae @zacharlie can this be closed?

**Comment by zacharlie** [comment]
I think it was resolved by @NyakudyaA scaling the platform containers
