### ISSUE TITLE
Create new layer of villages from the WDC and VDC

### ISSUE THREAD

**Issue by seabilwe** [kartoza/WBR-SEMP#96]
Create a point/polygon layer from the list of villages sent through (see attachment), create a point/polygon layer. Thereafter, use the layer for #95 

@gubuntu a few questions
From the SEMP project, how did you go about creating the layer of the survey villages?

- did you use google earth to locate the villages?
- was the layer initially a point
- what CRS did you create the layer from?
- would you prefer for the layer to go directly to the wbr database or be stored in a GPKG for now?

[WASH villages.docx](https://github.com/kartoza/WBR-SEMP/files/8751920/WASH.villages.docx)

**Comment by gubuntu** [comment]
identify them any way you can (from other datasets, OSM, satellite images, whatever) and add them to the existing village layer.

Many or most of them we used in the SEMP project

**Comment by seabilwe** [comment]
@gubuntu I have added the list of villages in the WASH + UNESCO folder: https://cloud.kartoza.com/s/s2sxASzsx32wtbE

There is only one village that needs to be added, Mamburu, I keep coming across Mapuru. I have asked Letticia about it, still waiting for a response.

I noticed that I don't have permission to edit the _survey_villages_ layer on the **wbr db**, its read-only permission.

but here is the gpkg with the newly added villages, please have a look at it, and then I can move to the main layer once I get the last village on. 
[wbr_vhembe_villages.zip](https://github.com/kartoza/WBR-SEMP/files/8754959/wbr_vhembe_villages.zip)

Also should I populate the attribute table with info from this village list provided or we won't have any need for it?

**Comment by NyakudyaA** [comment]
Hi, @seabilwe Are you having permission issues on the new DB ?. I can fix it for you

**Comment by seabilwe** [comment]
Not the new DB @NyakudyaA, it's from the WBR DB. I cant edit the layer to add new features to it.
