### ISSUE TITLE
a map of the WDC

### ISSUE THREAD

**Issue by seabilwe** [kartoza/WBR-SEMP#98]
From Richard:

"a map of the WDC, zooming in to show the position of the communities relative to one another"

**Comment by seabilwe** [comment]
@gubuntu 

All the villages
![WDC Villages 1](https://user-images.githubusercontent.com/56301949/171147785-2732f8c0-8131-4c20-8799-2e0ea6fad359.png)

![WDC Villages Zoomed In](https://user-images.githubusercontent.com/56301949/171147937-ba6fa956-fdc8-4a85-b40f-707ffcd6363d.png)

**Comment by gubuntu** [comment]
And the Vhembe villages?

Send maps to Richard

**Comment by seabilwe** [comment]
Only the Waterberg villages but I can make one Vhembe just in case

**Comment by seabilwe** [comment]
Maps submitted: 
![image](https://user-images.githubusercontent.com/56301949/217801691-0138e914-e550-4648-b5b2-bffaaa9862f1.png)
