### ISSUE TITLE
Separate maps of each village

### ISSUE THREAD

**Issue by seabilwe** [kartoza/WBR-SEMP#99]
From Richard:

"Separate maps of each village if there is sufficient info to illustrate the position of individual houses, roads etc – no idea if this is feasible without a lot of work on your part."

**Comment by seabilwe** [comment]
@gubuntu 

Here is the updated map of the villages. I used the OpenStreetMap basemap, instead of the NGI toposheet. Whenever the scale is set to, 25000 and the maps printed out, the toposheet does not render on the layout and is not printed. I opted for the OSM basemap and used the 1: 25000 scale because all individual village boundaries are not cut off.

Richard called me on WhatsApp asking if there is no basemap that shows street names, as he is concerned that the trainees will find it a bit difficult to navigate around the villages. So far the OSM basemap is a bit better, I have checked other basemaps and they dont give as much info.


[Wash Villages3.pdf](https://github.com/kartoza/WBR-SEMP/files/8803884/Wash.Villages3.pdf)

**Comment by gubuntu** [comment]
how about leaving out the village boundary and varying the scale to fit each village to the page

**Comment by seabilwe** [comment]
@gubuntu updated map
[WASH Villages Updated.pdf](https://github.com/kartoza/WBR-SEMP/files/8812361/WASH.Villages.Updated.pdf)

**Comment by gubuntu** [comment]
variable scale is nice, but please remove the boundaries, many of them are artificial. Let the street pattern speak for itself.

Do you not have any other layers with buildings? Microsoft, Facebook? aerial imagery in the background?

**Comment by seabilwe** [comment]
@gubuntu I used the Google hybrid basemap. It shows the buildings, roads, and landmarks depending on the area. Some areas do not have.
Here is the link to the file: https://drive.google.com/file/d/1l1Z6iUJm31BXUww1ynledZmcr5-3Gcto/view?usp=sharing

I will remove it from GDrive after you have had a look at it

**Comment by seabilwe** [comment]
And then this one uses the Bing Map, which does show buildings and roads and street names where available
[WASH Villages Bing Map.pdf](https://github.com/kartoza/WBR-SEMP/files/8813093/WASH.Villages.Bing.Map.pdf)

**Comment by seabilwe** [comment]
Maps submitted:
![image](https://user-images.githubusercontent.com/56301949/217802745-5950f7fc-a30a-4af5-9319-a6c123e02659.png)
